cmake_minimum_required(VERSION 3.16)
project(mnm_animation_model LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
add_library(mnm-animation-model STATIC no_cd.cpp)
target_include_directories(mnm-animation-model PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}" "${CMAKE_CURRENT_SOURCE_DIR}/../../assets")
target_compile_options(mnm-animation-model PRIVATE -Wall -Wextra -Werror -pedantic)
include(CTest)
if(BUILD_TESTING)
    add_executable(animation-model-test ../../tests/animation-model-test.cpp)
    target_link_libraries(animation-model-test PRIVATE mnm-animation-model)
    target_compile_options(animation-model-test PRIVATE -Wall -Wextra -Werror -pedantic)
    add_test(NAME animation-forward-model COMMAND animation-model-test)
endif()
