cmake_minimum_required(VERSION 3.16)
project(mnm_effect_animation_selection LANGUAGES CXX)
add_library(mnm-effect-animation-selection STATIC ../effect_animation_selection.cpp)
target_compile_features(mnm-effect-animation-selection PUBLIC cxx_std_17)
target_include_directories(mnm-effect-animation-selection PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/..")
target_compile_options(mnm-effect-animation-selection PRIVATE -Wall -Wextra -Werror -pedantic)
include(CTest)
if(BUILD_TESTING)
    add_executable(effect-animation-selection-test ../../../tests/effect-animation-selection-test.cpp)
    target_link_libraries(effect-animation-selection-test PRIVATE mnm-effect-animation-selection)
    target_compile_options(effect-animation-selection-test PRIVATE -Wall -Wextra -Werror -pedantic)
    add_test(NAME effect-animation-selection COMMAND effect-animation-selection-test)
endif()
