#include "character_screen_widget.hpp"
#include "menu_preview.hpp"
#include "main_menu_widget.hpp"
#include <QApplication>
#include <QDir>
#include <QFile>
#include <QKeyEvent>
#include <QLabel>
#include <QProgressBar>
#include <QPushButton>
#include <QRadioButton>
#include <QStackedWidget>
#include <QStatusBar>
#include <QTemporaryDir>
#include <cstdio>
#include <stdexcept>
static void require(bool ok,const char* why){if(!ok)throw std::runtime_error(why);}
static void write(const QString& path,const QByteArray& bytes){QFile file(path);require(file.open(QIODevice::WriteOnly)&&file.write(bytes)==bytes.size(),"fixture write");}
int main(int argc,char**argv) {
 QApplication app(argc,argv);
 try {
    QTemporaryDir temporary;require(temporary.isValid(),"temporary root");const auto root=temporary.path();require(QDir().mkpath(root+"/CFG"),"strings folder");
    QByteArray strings("[STRINGS]\n");for(int i=0;i<100;++i){const auto text=i==10?"OK":i==11?"Cancel":i==31?"Cornelius":i==32?"Experience Points":i==33?"Mana":i==34?"Health":i==35?"Control Limit":i==36?"Law Talismans":i==37?"Neutral Talismans":i==38?"Chaos Talismans":i==39?"Cost:":"Label";strings+=QString("STR_%1=%2\n").arg(i,2,10,QLatin1Char('0')).arg(text).toLatin1();}write(root+"/CFG/interface screens text.cfg",strings);
    QImage image(800,600,QImage::Format_RGB32);image.fill(QColor(90,120,150));const auto folder=root+"/Interface/CharacterScreen";require(QDir().mkpath(folder+"/800x600")&&image.save(folder+"/800x600/CharacterScreen.JPG","JPG"),"character image");
    QImage face(400,300,QImage::Format_RGB888);face.fill(QColor(0,0,255));
    for(int i=0;i<3;++i){face.fill(QColor(0,0,255));for(int y=80;y<120;++y)for(int x=80;x<120;++x)face.setPixelColor(x,y,QColor(180+i*20,130-i*20,80));require(face.save(folder+QString("/800x600/WizardFace%1.JPG").arg(i),"JPG"),"face JPEG");}
    const std::array<QString,3> textureNames{"Mana Bar.BMP","Health Bar.BMP","Control Limit Bar.BMP"};
    QImage texture(700,20,QImage::Format_RGB888);texture.fill(QColor(80,80,80));
    for(int y=0;y<20;++y)for(int x=0;x<350;++x)texture.setPixelColor(x,y,QColor(170,140,60));
    for(const auto& name:textureNames)require(texture.save(folder+"/800x600/"+name,"BMP"),"bar BMP");
    const std::array<QString,17> rectangles{"0,52,800,92","650,60,790,110","0,215,260,265","0,265,260,315","0,315,260,365","0,365,260,415","0,415,260,465","0,465,260,515","650,122,790,172","650,190,790,215","690,215,750,265","690,265,750,315","690,315,750,365","690,365,750,415","690,415,750,465","690,465,750,515","225,125,575,160"};
    const std::array<QString,6> variables{"VAR_MANACOST","VAR_HEALTHCOST","VAR_CONTROLCOST","VAR_LAWCOST","VAR_NEUTRALCOST","VAR_CHAOSCOST"};
    QByteArray layout("[GLOBALS]\nBackgroundFile=CharacterScreen\n");
    for(int i=0;i<17;++i){const auto text=i<8?QString::number(31+i):i==8?QString("VAR_EXPERIENCE"):i==9?QString("39"):i==16?QString("\"\""):variables[i-10];layout+=QString("[TEXT_%1]\nFont=%2\nRect2=%3\nText=%4\nTextFlags=%5\n").arg(i+1).arg(i==1||i==9?"SMALL":"LARGE").arg(rectangles[i],text,i>=2&&i<=7?"RIGHT":"CENTRE").toLatin1();}
    const std::array<int,3> maximum{200,800,40};
    for(int i=0;i<3;++i){layout+=QString("[STATBAR_%1]\nRect2=270,%2,620,%3\nminValue=0\nmaxValue=%4\nText=%8\n[SPRITEBAR_%1]\nRect2=270,%5,0,0\nminValue=0\nmaxValue=7\nSpriteIndexes=%6,%7\n").arg(i+1).arg(230+i*50).arg(250+i*50).arg(maximum[i]).arg(360+i*50).arg(i).arg(i+3).arg(textureNames[i]).toLatin1();}
    for(int i=0;i<12;++i)layout+=QString("[STANDARDBUTTON_%1]\nRect2=%2,%3,%4,%5\nSpriteIndexes=%6\n").arg(i+1).arg(i%2?750:660).arg(225+(i/2)*50).arg(i%2?780:690).arg(255+(i/2)*50).arg(i%2?"9,10,11":"6,7,8").toLatin1();
    layout+="[TEXTBUTTON_1]\nFont=LARGE\nRect2=40,530,280,570\nText=10\n[TEXTBUTTON_2]\nFont=LARGE\nRect2=530,530,760,570\nText=11\n[STEPS_COSTS]\nMana_IncrementAmount=5\nHealth_IncrementAmount=20\nControl_IncrementAmount=1\nTalisman_IncrementAmount=1\nMana_InitialCost=0\nMana_LinearComponent=.6\nMana_ExponentialComponent=1.3\n";
    const auto config=folder+"/screen (Character Screen).cfg";write(config,layout);
    CharacterScreenWidget widget;QString error;require(widget.loadAssets(root,&error)&&error.isEmpty(),"all configured roles and dynamic placeholders");widget.show();app.processEvents();
    auto adjust=[&](int n){return widget.findChild<QPushButton*>(QString("characterAdjustment%1").arg(n));};auto* ok=widget.findChild<QPushButton*>("characterOk");auto* cancel=widget.findChild<QPushButton*>("characterCancel");auto* xp=widget.findChild<QLabel*>("characterText9");
    require(!ok->isEnabled()&&!adjust(0)->isEnabled()&&widget.findChild<QLabel*>("characterText3")->text()=="Mana"&&widget.findChild<QLabel*>("characterText2")->text()=="Experience Points"&&ok->text()=="OK","static labels and empty-character guards");widget.focusFirstControl();require(cancel->hasFocus(),"empty focus");
    int accepted=0,cancelled=0;CharacterScreenWidget::Request submitted;QObject::connect(&widget,&CharacterScreenWidget::characterAccepted,&widget,[&](const auto& request){++accepted;submitted=request;});QObject::connect(&widget,&CharacterScreenWidget::cancelled,&widget,[&]{++cancelled;});
    CharacterScreenWidget::Character character;character.id="opaque-character";character.name="<b>Character</b>";character.portraitText="P1";character.rating="Sample rank";character.experiencePoints=100;const std::array<int,6> values{50,100,10,1,1,1};
    for(int i=0;i<6;++i){character.stats[i].value=values[i];character.stats[i].upgradeCosts={5,10};}
    require(widget.setCharacter(character,&error)&&ok->isEnabled()&&widget.findChild<QLabel*>("characterText1")->text()==character.name&&widget.findChild<QLabel*>("characterText1")->textFormat()==Qt::PlainText&&widget.findChild<QLabel*>("characterPortrait")->text()=="P1","caller snapshot and literal name");
    app.processEvents();auto rendered=widget.grab().toImage();
    require(rendered.pixelColor(280,240)==QColor(170,140,60)&&rendered.pixelColor(610,240)==QColor(80,80,80),"active and inactive BMP halves follow supplied value");
    auto withFace=character;withFace.portraitIndex=1;require(widget.setCharacter(withFace,&error),"explicit portrait selection");app.processEvents();
    const auto pixmap=widget.findChild<QLabel*>("characterPortrait")->pixmap();
    require(!pixmap.isNull()&&pixmap.size()==QSize(400,300)&&pixmap.toImage().pixelColor(20,20).alpha()==0,"decoded portrait owned and blue backdrop removed");
    const auto faceColor=pixmap.toImage().pixelColor(100,100);require(qAbs(faceColor.red()-200)<5&&qAbs(faceColor.green()-110)<5,"caller-selected face uses correct decoded image");
    widget.resize(1200,600);app.processEvents();require(widget.findChild<QLabel*>("characterPortrait")->geometry()==QRect(200,0,400,300),"portrait follows letterboxed canvas");
    widget.resize(400,300);app.processEvents();require(widget.findChild<QLabel*>("characterPortrait")->pixmap().size()==QSize(200,150),"portrait scales with canvas");widget.resize(800,600);app.processEvents();
    auto invalidFace=withFace;invalidFace.portraitIndex=3;require(!widget.setCharacter(invalidFace,&error)&&widget.character().portraitIndex==1,"invalid face preserves snapshot");
    require(widget.setCharacter(character,&error),"text portrait fallback restored");
    const std::array<int,6> increments{5,20,1,1,1,1};
    for(int i=0;i<6;++i){require(adjust(2*i)->isEnabled()&&!adjust(2*i+1)->isEnabled(),"no refund of baseline stats");adjust(2*i)->click();require(widget.draftRequest().values[i]==values[i]+increments[i]&&widget.findChild<QLabel*>(QString("characterText%1").arg(11+i))->text()=="10","configured increment and next caller cost");}
    require(widget.draftRequest().remainingExperience==70&&xp->text()=="70"&&widget.character().experiencePoints==100&&widget.character().stats[0].value==50,"draft purchases do not mutate accepted snapshot");
    require(widget.findChild<QProgressBar*>("characterStatBar0")->value()==55&&widget.findChild<QProgressBar*>("characterStatBar1")->value()==120&&widget.findChild<QLabel*>("characterTalisman0")->text()=="2 / 7","bar and talisman displays follow draft");adjust(1)->click();require(widget.draftRequest().remainingExperience==75&&widget.draftRequest().values[0]==50&&!adjust(1)->isEnabled(),"undo refunds exact supplied cost");adjust(0)->click();adjust(0)->click();require(widget.draftRequest().remainingExperience==60&&widget.draftRequest().values[0]==60&&!adjust(0)->isEnabled()&&widget.findChild<QLabel*>("characterText11")->text()=="—","finite supplied cost schedule");adjust(1)->click();require(widget.draftRequest().remainingExperience==70,"undo second increment refunds second cost");
    QKeyEvent enter(QEvent::KeyPress,Qt::Key_Return,Qt::NoModifier),repeat(QEvent::KeyPress,Qt::Key_Return,Qt::NoModifier,QString(),true),escape(QEvent::KeyPress,Qt::Key_Escape,Qt::NoModifier);
    QApplication::sendEvent(adjust(0),&enter);require(widget.draftRequest().values[0]==60&&accepted==0,"Enter on plus edits once without accepting");QApplication::sendEvent(adjust(0),&repeat);require(widget.draftRequest().values[0]==60,"repeat ignored");QApplication::sendEvent(cancel,&enter);require(cancelled==1&&widget.draftRequest().remainingExperience==100&&widget.draftRequest().values==values,"Cancel rolls back all edits");
    adjust(0)->click();adjust(6)->click();ok->click();require(accepted==1&&submitted.characterId=="opaque-character"&&submitted.remainingExperience==90&&submitted.values[0]==55&&submitted.values[3]==2&&submitted.purchasedIncrements[0]==1&&submitted.purchasedIncrements[3]==1,"complete typed allocation snapshot");require(widget.character().experiencePoints==90&&widget.character().stats[0].value==55&&widget.character().stats[0].upgradeCosts.size()==1&&!adjust(1)->isEnabled()&&widget.draftRequest().purchasedIncrements[0]==0,"local acceptance advances baseline and price schedule");adjust(0)->click();QApplication::sendEvent(adjust(0),&escape);require(cancelled==2&&widget.draftRequest().values[0]==55&&widget.draftRequest().remainingExperience==90,"Escape rolls back to last local acceptance");
    auto low=character;low.experiencePoints=4;require(widget.setCharacter(low)&&!adjust(0)->isEnabled(),"insufficient experience guard");low.experiencePoints=5;require(widget.setCharacter(low)&&adjust(0)->isEnabled(),"exact budget permitted");adjust(0)->click();require(widget.draftRequest().remainingExperience==0&&!adjust(2)->isEnabled()&&adjust(1)->isEnabled(),"shared budget across stats");adjust(1)->click();require(widget.draftRequest().remainingExperience==5,"exact refund");
    auto free=character;free.experiencePoints=0;free.stats[0].upgradeCosts={0};require(widget.setCharacter(free)&&adjust(0)->isEnabled(),"explicit zero-cost caller price");adjust(0)->click();require(widget.draftRequest().remainingExperience==0&&widget.draftRequest().values[0]==55,"zero-cost purchase bounded by schedule");
    auto limited=character;limited.stats[0].value=195;limited.stats[0].upgradeCosts={5};limited.stats[1].upgradeAvailable=false;require(widget.setCharacter(limited)&&!adjust(2)->isEnabled(),"caller upgrade availability");adjust(0)->click();require(widget.draftRequest().values[0]==200&&!adjust(0)->isEnabled(),"configured maximum");
    require(widget.setCharacter(character),"restore snapshot");auto invalid=character;invalid.stats[0].value=201;require(!widget.setCharacter(invalid,&error)&&!error.isEmpty()&&widget.character().stats[0].value==50,"range rejection transactional");invalid=character;invalid.stats[0].upgradeCosts={-1};require(!widget.setCharacter(invalid,&error),"negative cost rejected");invalid=character;invalid.stats[0].value=195;require(!widget.setCharacter(invalid,&error),"price schedule beyond capacity rejected");invalid=character;invalid.experiencePoints=-1;require(!widget.setCharacter(invalid,&error),"negative budget rejected");invalid=character;invalid.name.clear();require(!widget.setCharacter(invalid,&error),"partial identity rejected");
    adjust(0)->click();write(config,QByteArray(layout).replace("Mana_IncrementAmount=5","Mana_IncrementAmount=10"));require(!widget.loadAssets(root,&error)&&widget.draftRequest().values[0]==55&&xp->text()=="95","increment reload cannot reinterpret pending edits");write(config,QByteArray(layout).replace("Rect2=270,360,0,0","Rect2=700,360,0,0"));require(!widget.loadAssets(root,&error)&&widget.draftRequest().values[0]==55,"invalid anchor rejected");write(config,QByteArray(layout).replace("SpriteIndexes=6,7,8","SpriteIndexes=9,10,11"));require(!widget.loadAssets(root,&error),"adjustment role rejected");write(config,QByteArray(layout).replace("Text=VAR_EXPERIENCE","Text=31"));require(!widget.loadAssets(root,&error),"dynamic role rejected");write(config,layout);require(widget.loadAssets(root,&error)&&widget.draftRequest().values[0]==55&&xp->text()=="95","valid reload retains draft");
    widget.resize(1200,600);app.processEvents();require(widget.contentRect()==QRect(200,0,800,600)&&adjust(0)->geometry()==QRect(860,225,30,30)&&widget.findChild<QLabel*>("characterTalisman0")->geometry()==QRect(470,375,350,30),"wide geometry and sprite-anchor replacement");const auto capture=widget.grab().toImage();require(capture.pixelColor(10,10)==QColor(Qt::black)&&qAbs(capture.pixelColor(600,590).blue()-150)<4,"background and letterbox");widget.resize(400,600);app.processEvents();require(adjust(0)->geometry()==QRect(330,263,15,15),"scaled buttons");
    for(const auto& entry:std::array<std::pair<QString,QString>,2>{{{"MainScreen","screen (MainMenu).cfg"},{"QuickBattleMainMenu","Screen (Quick Battle Main Menu).cfg"}}}){const auto path=root+"/Interface/"+entry.first;require(QDir().mkpath(path+"/800x600")&&image.save(path+"/800x600/Fixture 800-600.JPG","JPG"),"navigation image");QByteArray cfg("[GLOBALS]\nBackgroundFile=Fixture\n[TEXT_1]\nRect2=100,50,700,100\nText=0\n");for(int i=0;i<6;++i)cfg+=QString("[TEXTBUTTON_%1]\nRect2=150,%2,650,%3\nText=%4\n").arg(i+1).arg(200+i*50).arg(240+i*50).arg(i).toLatin1();write(path+"/"+entry.second,cfg);}
    const auto regionPath=root+"/Interface/RegionEntry";require(QDir().mkpath(regionPath+"/800x600")&&image.save(regionPath+"/800x600/Celtic_Region_01.JPG","JPG"),"region image");QByteArray regionLayout("[GLOBAL]\n[TEXT_1]\nRect2=50,40,525,75\nFont=LARGE\nTextFlags=LEFT\nText=Current Region\n[TEXTBUTTON_1]\nRect2=50,510,325,560\nFont=LARGE\nText=78\n[TEXTBUTTON_2]\nRect2=475,510,750,560\nFont=LARGE\nText=11\n");for(int i=0;i<4;++i)regionLayout+=QString("[RADIOBUTTON_%1]\nRect2=%2,90,%3,115\nFont=SMALL\nText=%4\n").arg(i+1).arg(50+i*175).arg(225+i*175).arg(79+i).toLatin1();const std::array<int,3> first{3,6,0};for(int i=0;i<3;++i)regionLayout+=QString("[STANDARDBUTTON_%1]\nRect2=%2,25,%3,85\nSpriteIndexes=%4,%5,%6\n").arg(i+1).arg(585+i*65).arg(645+i*65).arg(first[i]).arg(first[i]+1).arg(first[i]+2).toLatin1();write(regionPath+"/screen (Region Entry).cfg",regionLayout);
    widget.hide();MenuPreview preview;require(preview.loadAssets(root,false,&error)&&preview.openRegionEntry(root,&error),"preview region route");preview.show();app.processEvents();auto* stack=preview.findChild<QStackedWidget*>();auto* region=preview.findChild<RegionEntryWidget*>();region->findChild<QRadioButton*>("regionEntryDifficulty3")->click();region->findChild<QPushButton*>("regionEntryAuxiliary2")->click();auto* screen=qobject_cast<CharacterScreenWidget*>(stack->currentWidget());require(screen&&screen->character().id=="sample-character","Character button opens supplied preview");screen->findChild<QPushButton*>("characterAdjustment0")->click();screen->findChild<QPushButton*>("characterCancel")->click();require(stack->currentWidget()==region&&region->region().difficulty==RegionEntryWidget::Difficulty::Wizard&&region->findChild<QPushButton*>("regionEntryAuxiliary2")->hasFocus()&&screen->draftRequest().values[0]==50,"Cancel rolls back and restores Region caller/focus");region->findChild<QPushButton*>("regionEntryAuxiliary2")->click();screen->findChild<QPushButton*>("characterAdjustment0")->click();screen->findChild<QPushButton*>("characterOk")->click();require(stack->currentWidget()==region&&screen->character().stats[0].value==55&&preview.statusBar()->currentMessage().contains("accepted locally")&&preview.statusBar()->currentMessage().contains("adapter pending"),"OK returns Region and retains local accepted snapshot");region->findChild<QPushButton*>("regionEntryAuxiliary2")->click();require(screen->draftRequest().values[0]==55&&screen->character().experiencePoints==95,"reopen retains acceptance");screen->findChild<QPushButton*>("characterCancel")->click();
    write(config,"bad layout");region->findChild<QPushButton*>("regionEntryAuxiliary2")->click();require(stack->currentWidget()==region&&region->region().difficulty==RegionEntryWidget::Difficulty::Wizard&&preview.statusBar()->currentMessage().contains("failed"),"asset failure preserves Region caller");write(config,layout);region->findChild<QPushButton*>("regionEntryCancel")->click();require(preview.openCharacterScreen(root,&error),"standalone Character route");screen->findChild<QPushButton*>("characterCancel")->click();require(stack->currentWidget()==preview.findChild<MainMenuWidget*>(),"standalone Cancel returns Main");
    write(folder+"/800x600/Mana Bar.BMP","bad BMP");require(!widget.loadAssets(root,&error)&&widget.draftRequest().values[0]==55,"corrupt texture preserves draft");require(texture.save(folder+"/800x600/Mana Bar.BMP","BMP"),"restore texture");
    write(folder+"/800x600/WizardFace2.JPG","bad JPEG");require(!widget.loadAssets(root,&error)&&widget.draftRequest().values[0]==55,"corrupt portrait preserves draft");require(face.save(folder+"/800x600/WizardFace2.JPG","JPG"),"restore portrait");
    write(folder+"/800x600/CharacterScreen.JPG","bad JPEG");require(!widget.loadAssets(root,&error)&&widget.draftRequest().values[0]==55,"corrupt background preserves draft");return 0;
 }catch(const std::exception& failure){std::fprintf(stderr,"Character Screen test: %s\n",failure.what());return 1;}
}
