#include "grimoire_widget.hpp"
#include "menu_preview.hpp"
#include "main_menu_widget.hpp"
#include "grimoire-fixtures.hpp"
#include <QApplication>
#include <QKeyEvent>
#include <QLabel>
#include <QListWidget>
#include <QRadioButton>
#include <QStackedWidget>
#include <QStatusBar>
#include <QTemporaryDir>
#include <QTextBrowser>
#include <cstdio>
static void require(bool value,const char* why){if(!value)throw std::runtime_error(why);}
int main(int argc,char**argv) {
 QApplication app(argc,argv);
 try {
    QTemporaryDir temporary;require(temporary.isValid(),"temporary root");const auto root=temporary.path(),folder=grimoire_fixture::create(root);GrimoireWidget widget;QString error;
    require(widget.loadAssets(root,&error)&&error.isEmpty(),"synthetic book and artwork load");widget.show();app.processEvents();
    auto* list=widget.findChild<QListWidget*>("grimoireEntries");auto* text=widget.findChild<QTextBrowser*>("grimoireText");auto* title=widget.findChild<QLabel*>("grimoireTitle");
    auto button=[&](const char* name){return widget.findChild<QPushButton*>(name);};
    require(widget.book().chapters.size()==8&&list->count()==2&&list->item(0)->text()=="Zulu"&&widget.book().chapters[4].entries[0].section==1,"all chapters, source order and configured sorting");
    require(!button("grimoirePrevious")->isEnabled()&&!button("grimoireContents")->isEnabled(),"first contents boundaries");
    int changed=0,closed=0,failed=0;QObject::connect(&widget,&GrimoireWidget::pageChanged,&widget,[&](auto){++changed;});QObject::connect(&widget,&GrimoireWidget::closed,&widget,[&]{++closed;});QObject::connect(&widget,&GrimoireWidget::navigationFailed,&widget,[&](const auto&){++failed;});
    widget.focusFirstControl();require(list->hasFocus(),"contents focus");QKeyEvent enter(QEvent::KeyPress,Qt::Key_Return,Qt::NoModifier),repeat(QEvent::KeyPress,Qt::Key_Return,Qt::NoModifier,QString(),true),escape(QEvent::KeyPress,Qt::Key_Escape,Qt::NoModifier),down(QEvent::KeyPress,Qt::Key_PageDown,Qt::NoModifier),up(QEvent::KeyPress,Qt::Key_PageUp,Qt::NoModifier);
    QApplication::sendEvent(list,&repeat);require(widget.location().section==0,"contents repeat suppressed");
    QApplication::sendEvent(list,&enter);require(widget.location().section==2&&widget.location().level==1&&!list->isVisible()&&text->toPlainText().contains("Second paragraph.")&&text->toPlainText().contains("Mana: —")&&!text->toPlainText().contains("payload"),"entry activation and non-fabricated dynamic values");
    require(button("grimoireArtwork")->isEnabled(),"companion illustration available");button("grimoireArtwork")->click();require(widget.location().illustration&&!text->isVisible()&&button("grimoireArtwork")->text()=="Read"&&qAbs(widget.grab().toImage().pixelColor(600,400).green()-140)<4,"two-page artwork mode renders companion");button("grimoireArtwork")->click();require(!widget.location().illustration&&text->isVisible(),"Read restores prose");
    QApplication::sendEvent(button("grimoireNext"),&enter);require(widget.location().page==1&&text->toPlainText().startsWith("Second text page."),"explicit text page directive");QApplication::sendEvent(button("grimoireNext"),&repeat);require(widget.location().page==1,"button repeat suppressed");QApplication::sendEvent(text,&down);require(widget.location().section==1&&widget.location().page==0&&title->text()=="<b>Alpha</b>"&&title->textFormat()==Qt::PlainText,"next section and literal title");QApplication::sendEvent(text,&up);require(widget.location().section==2&&widget.location().page==1,"previous page returns prior section tail");
    button("grimoireContents")->click();require(widget.location().section==0&&list->isVisible(),"chapter contents return");
    for(int i=0;i<8;++i){widget.findChild<QPushButton*>(QString("grimoireTab%1").arg(i))->click();require(widget.location().chapter==i&&widget.location().section==0,"all chapter tabs");widget.findChild<QPushButton*>(QString("grimoireTab%1").arg(i+8))->click();require(widget.location().chapter==i,"mirrored tabs");}
    require(widget.setLocation({7,2,1,1},&error)&&!button("grimoireNext")->isEnabled(),"last page bound in sorted chapter");button("grimoireNext")->click();require(widget.location().page==1,"no wrap at end");require(!widget.setLocation({8,0,0,0},&error)&&!widget.setLocation({7,2,0,0},&error)&&!widget.setLocation({7,0,0,1},&error)&&!widget.setLocation({7,1,0,0,true},&error)&&widget.location().section==2,"invalid chapter/knowledge/page rejection");
    QFile config(folder+"/Grimoire.cfg");require(config.open(QIODevice::ReadOnly),"read fixture config");const auto goodCfg=config.readAll();config.close();grimoire_fixture::write(folder+"/Grimoire.cfg",QByteArray(goodCfg).replace("800x600_X=773","800x600_X=799"));require(!widget.loadAssets(root,&error)&&widget.location().section==2,"layout rejection preserves reader");grimoire_fixture::write(folder+"/Grimoire.cfg",goodCfg);
    QFile source(folder+"/Grimoire.txt");require(source.open(QIODevice::ReadOnly),"read source fixture");const auto goodText=source.readAll();source.close();
    for(const auto& bad:{QByteArray("~[ unclosed"),QByteArray(goodText).replace("~L1","~L9"),QByteArray(goodText).replace("~D \"Mana\"","~UNKNOWN \"Mana\""),QByteArray(goodText)+"\n~C0-000-\"Duplicate\"\n"}){grimoire_fixture::write(folder+"/Grimoire.txt",bad);require(!widget.loadAssets(root,&error)&&widget.location().section==2,"invalid source preserves book and location");}grimoire_fixture::write(folder+"/Grimoire.txt",goodText);
    grimoire_fixture::write(folder+"/800x600/C7S01P1_Broken.JPG","bad JPEG");require(widget.loadAssets(root,&error),"unvisited art is lazy");require(!widget.setLocation({7,1,0,0},&error)&&widget.location().section==2,"corrupt visited illustration preserves spread");button("grimoirePrevious")->click();button("grimoirePrevious")->click();require(failed==1&&widget.location().section==2,"failed page turn preserves location and reports error");require(QFile::remove(folder+"/800x600/C7S01P1_Broken.JPG"),"remove broken art");require(widget.loadAssets(root,&error),"restore catalog");
    menu_sprite_fixture::write(root,"Interface/Grimoire/800x600/icons.spr",3);require(!widget.loadAssets(root,&error)&&widget.location().section==2,"sprite catalog rollback");menu_sprite_fixture::write(root,"Interface/Grimoire/800x600/icons.spr",34);
    widget.resize(1200,600);app.processEvents();require(widget.contentRect()==QRect(200,0,800,600)&&button("grimoireClose")->geometry()==QRect(973,238,27,116),"wide canvas/control alignment");const auto capture=widget.grab().toImage();require(capture.pixelColor(10,10)==QColor(Qt::black)&&qAbs(capture.pixelColor(290,550).red()-130)<5,"letterbox and keyed page exposes parchment");widget.resize(400,600);app.processEvents();require(button("grimoirePrevious")->geometry()==QRect(38,417,23,18),"scaled controls");QApplication::sendEvent(text,&escape);require(closed==1&&changed>10,"Escape from text closes");
    // Native preview caller navigation uses only synthetic menu data/art.
    require(QDir().mkpath(root+"/CFG"),"strings dir");QByteArray strings("[STRINGS]\n");for(int i=0;i<100;++i)strings+=QString("STR_%1=Label %2\n").arg(i,2,10,QLatin1Char('0')).arg(i).toLatin1();grimoire_fixture::write(root+"/CFG/interface screens text.cfg",strings);menu_sprite_fixture::shared(root);
    QImage image(800,600,QImage::Format_RGB888);image.fill(QColor(90,120,150));
    for(const auto& dir:{QString("MainScreen"),QString("QuickBattleMainMenu"),QString("RegionEntry")})require(QDir().mkpath(root+"/Interface/"+dir+"/800x600"),"menu folders");
    for(const auto& dir:{QString("MainScreen"),QString("QuickBattleMainMenu")}){require(image.save(root+"/Interface/"+dir+"/800x600/Fixture 800-600.JPG","JPG"),"menu art");QByteArray cfg("[GLOBALS]\nBackgroundFile=Fixture\n[TEXT_1]\nRect2=100,50,700,100\nText=0\n");for(int i=0;i<6;++i)cfg+=QString("[TEXTBUTTON_%1]\nRect2=150,%2,650,%3\nText=%4\n").arg(i+1).arg(200+i*50).arg(240+i*50).arg(i).toLatin1();grimoire_fixture::write(root+"/Interface/"+dir+"/"+(dir=="MainScreen"?"screen (MainMenu).cfg":"Screen (Quick Battle Main Menu).cfg"),cfg);}
    require(image.save(root+"/Interface/RegionEntry/800x600/Celtic_Region_01.JPG","JPG"),"region art");QByteArray regionCfg("[TEXT_1]\nFont=LARGE\nTextFlags=LEFT\nRect2=50,40,525,75\nText=Region\n[TEXTBUTTON_1]\nFont=LARGE\nRect2=50,510,325,560\nText=78\n[TEXTBUTTON_2]\nFont=LARGE\nRect2=475,510,750,560\nText=11\n");for(int i=0;i<4;++i)regionCfg+=QString("[RADIOBUTTON_%1]\nFont=SMALL\nRect2=%2,90,%3,115\nText=%4\n").arg(i+1).arg(50+i*175).arg(225+i*175).arg(79+i).toLatin1();const std::array<int,3> first{3,6,0};for(int i=0;i<3;++i)regionCfg+=QString("[STANDARDBUTTON_%1]\nRect2=%2,25,%3,85\nSpriteIndexes=%4,%5,%6\n").arg(i+1).arg(585+i*65).arg(645+i*65).arg(first[i]).arg(first[i]+1).arg(first[i]+2).toLatin1();grimoire_fixture::write(root+"/Interface/RegionEntry/screen (Region Entry).cfg",regionCfg);
    widget.hide();MenuPreview preview;require(preview.loadAssets(root,false,&error)&&preview.openRegionEntry(root,&error),"Region preview route");preview.show();app.processEvents();auto* region=preview.findChild<RegionEntryWidget*>();auto* stack=preview.findChild<QStackedWidget*>();region->findChild<QRadioButton*>("regionEntryDifficulty3")->click();region->findChild<QPushButton*>("regionEntryAuxiliary0")->click();auto* reader=qobject_cast<GrimoireWidget*>(stack->currentWidget());require(reader&&reader->setLocation({4,1,0,0},&error),"Grimoire icon opens book");reader->findChild<QPushButton*>("grimoireClose")->click();require(stack->currentWidget()==region&&region->region().difficulty==RegionEntryWidget::Difficulty::Wizard&&region->findChild<QPushButton*>("regionEntryAuxiliary0")->hasFocus(),"close restores Region difficulty and focus");region->findChild<QPushButton*>("regionEntryAuxiliary0")->click();require(reader->location().chapter==4&&reader->location().section==1,"reopen preserves reading location");reader->findChild<QPushButton*>("grimoireClose")->click();grimoire_fixture::write(folder+"/Grimoire.txt","bad book");region->findChild<QPushButton*>("regionEntryAuxiliary0")->click();require(stack->currentWidget()==region&&preview.statusBar()->currentMessage().contains("failed"),"opening failure retains caller");grimoire_fixture::write(folder+"/Grimoire.txt",goodText);region->findChild<QPushButton*>("regionEntryCancel")->click();require(preview.openGrimoire(root,&error),"standalone route");reader->findChild<QPushButton*>("grimoireClose")->click();require(stack->currentWidget()==preview.findChild<MainMenuWidget*>(),"standalone returns Main");return 0;
 }catch(const std::exception& failure){std::fprintf(stderr,"Grimoire test: %s\n",failure.what());return 1;}
}
