#include "menu-sprite-fixtures.hpp"
#include "multiplayer_lobby_widget.hpp"
#include "menu_preview.hpp"
#include "multiplayer-lobby-fixtures.hpp"
#include <QApplication>
#include <QKeyEvent>
#include <QLabel>
#include <QLineEdit>
#include <QListWidget>
#include <QPlainTextEdit>
#include <QPushButton>
#include <QSlider>
#include <QStackedWidget>
#include <QStatusBar>
#include <QTemporaryDir>
#include <cstdio>
using lobby_fixture::require;
using lobby_fixture::write;
int main(int argc,char**argv) {
 QApplication app(argc,argv);
 try {
    QTemporaryDir temporary;require(temporary.isValid(),"temporary root");const auto root=temporary.path();require(QDir().mkpath(root+"/CFG"),"strings directory");
    QByteArray strings("[STRINGS]\n");for(int i=0;i<100;++i){const auto text=i==11?"Cancel":i==52?"Map":i==53?"Start":i==54?"Ready":i==55?"No Player":i==56?"Handicap":"Label";strings+=QString("STR_%1=%2\n").arg(i,2,10,QLatin1Char('0')).arg(text).toLatin1();}write(root+"/CFG/interface screens text.cfg",strings);
    menu_sprite_fixture::shared(root);QImage image(800,600,QImage::Format_RGB32);image.fill(QColor(90,120,150));const auto layouts=lobby_fixture::create(root,image);
    QKeyEvent enter(QEvent::KeyPress,Qt::Key_Return,Qt::NoModifier),repeat(QEvent::KeyPress,Qt::Key_Return,Qt::NoModifier,QString(),true),escape(QEvent::KeyPress,Qt::Key_Escape,Qt::NoModifier);
    for(auto mode:{MultiplayerLobbyWidget::Mode::Host,MultiplayerLobbyWidget::Mode::Join}) {
        const bool host=mode==MultiplayerLobbyWidget::Mode::Host;MultiplayerLobbyWidget widget(mode);QString error;require(widget.loadAssets(root,&error)&&error.isEmpty(),"base and mode assets");widget.show();app.processEvents();
        auto button=[&](const QString& name){return widget.findChild<QPushButton*>("multiplayerLobby"+name);};auto slider=[&](int n){return widget.findChild<QSlider*>(QString("multiplayerLobbySlider%1").arg(n));};
        auto* composer=widget.findChild<QLineEdit*>("multiplayerLobbyComposer");auto* chat=widget.findChild<QPlainTextEdit*>("multiplayerLobbyChat");
        require(button("Cancel")->text()=="Cancel"&&button("Start")->text()==(host?"Start":"Ready")&&!button("Start")->isEnabled()&&!composer->isEnabled(),"mode labels and initial guards");
        MultiplayerLobbyWidget::Lobby lobby;lobby.sessionId="opaque-session";lobby.gameName="Named game";lobby.mapId="opaque-map";lobby.mapName="Named map";lobby.localSlot=host?0:1;
        for(int i=0;i<4;++i) {lobby.players[i]={true,QString("Player %1").arg(i),"wizard","W1",QString::number(i),"Red",i*5};}
        require(widget.setLobby(lobby,&error)&&button("Start")->isEnabled(),"supplied lobby");widget.focusFirstControl();require(composer->hasFocus(),"chat focus");
        auto pictured=lobby;const int local=lobby.localSlot;pictured.players[local].portraitIndex=11;pictured.players[local].colourIndex=7;require(widget.setLobby(pictured,&error),"explicit local sprite choices");
        auto* portrait=button(QString("Portrait%1").arg(local));QEvent leave(QEvent::Leave);QApplication::sendEvent(portrait,&leave);portrait->clearFocus();
        require(portrait->grab().toImage().pixelColor(3,2)==QColor(Qt::red),"local selected portrait rendered");
        auto invalidArt=pictured;invalidArt.players[local].colourIndex=8;require(!widget.setLobby(invalidArt,&error)&&widget.lobby().players[local].colourIndex==7,"invalid local artwork rejected");
        menu_sprite_fixture::write(root,"Interface/MultiplayerBattleSetup/MultiPBattle Screen buttons 800-600.spr",3);require(!widget.loadAssets(root,&error)&&widget.lobby().players[local].portraitIndex==11,"short SPR sheet rollback preserves lobby");menu_sprite_fixture::shared(root);require(widget.loadAssets(root,&error)&&widget.setLobby(lobby,&error),"sprite reload and text fallback");
        require(widget.findChild<QLabel*>("multiplayerLobbyText13")->text()=="Named game"&&widget.findChild<QLabel*>("multiplayerLobbyText14")->text()=="Named map"&&!widget.findChild<QLabel*>("multiplayerLobbyText9")->isVisible(),"dynamic title map and hidden overlapping caption");
        int starts=0,readyCount=0,cancels=0,maps=0,profile=-1,colour=-1,removed=-1,chats=0;bool ready=false;QString sent;MultiplayerLobbyWidget::Lobby submitted;
        QObject::connect(&widget,&MultiplayerLobbyWidget::startRequested,&widget,[&](const auto& value){++starts;submitted=value;});QObject::connect(&widget,&MultiplayerLobbyWidget::readyRequested,&widget,[&](bool value){++readyCount;ready=value;});QObject::connect(&widget,&MultiplayerLobbyWidget::cancelled,&widget,[&]{++cancels;});QObject::connect(&widget,&MultiplayerLobbyWidget::mapRequested,&widget,[&]{++maps;});QObject::connect(&widget,&MultiplayerLobbyWidget::playerChangeRequested,&widget,[&](int slot){profile=slot;});QObject::connect(&widget,&MultiplayerLobbyWidget::colourChangeRequested,&widget,[&](int slot){colour=slot;});QObject::connect(&widget,&MultiplayerLobbyWidget::playerRemovalRequested,&widget,[&](int slot){removed=slot;});QObject::connect(&widget,&MultiplayerLobbyWidget::chatRequested,&widget,[&](const QString& text){++chats;sent=text;});
        require(button("Map")->isVisible()==host&&slider(1)->isVisible()==host&&button("Remove1")->isVisible()==host,"host-only controls");
        for(int i=0;i<4;++i){require(button(QString("Portrait%1").arg(i))->isEnabled()==(i==lobby.localSlot)&&button(QString("Colour%1").arg(i))->isEnabled()==(i==lobby.localSlot)&&slider(14+i)->isEnabled()==(host||i==lobby.localSlot),"local and remote edit policy");button(QString("Portrait%1").arg(i))->click();button(QString("Colour%1").arg(i))->click();}require(profile==lobby.localSlot&&colour==lobby.localSlot,"only local player requests");
        if(host){slider(1)->setValue(156);require(widget.lobby().values[0]==160&&widget.findChild<QLabel*>("multiplayerLobbyText28")->text()=="160","host snap and numeric label");button("Remove1")->click();require(removed==1,"host boot guest");button("Map")->click();require(maps==1,"host Map intent");button("Start")->click();require(starts==1&&submitted.sessionId=="opaque-session"&&submitted.values[0]==160&&submitted.localSlot==0,"host typed Start");}
        else{slider(1)->setValue(160);slider(14)->setValue(20);require(widget.lobby().values[0]==50&&widget.lobby().players[0].handicap==0,"guest cannot mutate hidden rules or remote handicap");slider(15)->setValue(17);require(widget.lobby().players[1].handicap==15,"guest local handicap");button("Start")->click();require(readyCount==1&&ready&&widget.lobby().localReady&&starts==0,"guest Ready intent");QApplication::sendEvent(button("Start"),&enter);require(readyCount==2&&!ready&&!widget.lobby().localReady,"Ready toggles off with Enter");QApplication::sendEvent(button("Start"),&repeat);require(readyCount==2,"Ready repeat suppressed");}
        const int before=starts;composer->setText("   ");QApplication::sendEvent(composer,&enter);require(chats==0&&starts==before,"blank chat cannot start");composer->setText("  <b>literal chat</b>  ");QApplication::sendEvent(composer,&enter);require(chats==1&&sent=="<b>literal chat</b>"&&composer->text().isEmpty()&&starts==before,"chat trims sends once and clears without starting");composer->setText("held draft");QApplication::sendEvent(composer,&repeat);require(chats==1&&composer->text()=="held draft","chat repeat ignored");QApplication::sendEvent(chat,&enter);require(starts==before&&chats==1,"reading chat cannot start");
        const QVector<MultiplayerLobbyWidget::Message> initialMessages{{"Other","<b>literal</b>"}},invalidMessages{{"","Bad"}};
        require(widget.setMessages(initialMessages,&error)&&chat->toPlainText()=="Other: <b>literal</b>","messages plain text");for(int i=0;i<105;++i)require(widget.appendMessage({"Player",QString::number(i)},&error),"bounded append");require(widget.messages().size()==100&&widget.messages().front().text=="5"&&widget.messages().back().text=="104","bounded history retains latest messages");const auto previous=chat->toPlainText();require(!widget.setMessages(invalidMessages,&error)&&!error.isEmpty()&&chat->toPlainText()==previous,"invalid history is transactional");require(!widget.appendMessage({"Player","two\nlines"},&error)&&widget.messages().size()==100&&chat->toPlainText()==previous,"invalid append preserves history");
        auto invalid=lobby;invalid.values[0]=51;require(!widget.setLobby(invalid,&error)&&widget.lobby().sessionId=="opaque-session","off-step model rejected");invalid=lobby;invalid.localSlot=4;require(!widget.setLobby(invalid,&error),"invalid local slot");invalid=lobby;invalid.mapName.clear();require(!widget.setLobby(invalid,&error),"partial map");if(host){invalid=lobby;invalid.localReady=true;require(!widget.setLobby(invalid,&error),"host has no Ready state");}
        auto inactive=lobby;inactive.players[inactive.localSlot].active=false;require(widget.setLobby(inactive)&&!button("Start")->isEnabled()&&!composer->isEnabled(),"inactive local actions disabled");require(widget.setLobby(lobby),"restore model");
        QApplication::sendEvent(composer,&escape);QApplication::sendEvent(button("Cancel"),&enter);require(cancels==2,"Escape and focused Cancel");
        widget.resize(1200,600);app.processEvents();require(widget.contentRect()==QRect(200,0,800,600)&&composer->geometry()==QRect(225,540,749,35)&&chat->geometry()==QRect(225,325,350,200),"wide lobby geometry");const auto capture=widget.grab().toImage();require(capture.pixelColor(10,10)==QColor(Qt::black)&&qAbs(capture.pixelColor(210,590).blue()-150)<4,"background and letterboxing");widget.resize(400,600);app.processEvents();require(composer->geometry()==QRect(13,420,375,18),"scaled composer");
        write(layouts.hostPath,QByteArray(layouts.host).replace("step=10","step=0"));require(!widget.loadAssets(root,&error)&&widget.lobby().sessionId=="opaque-session"&&composer->text()=="held draft"&&chat->toPlainText()==previous,"invalid overlay preserves model chat and draft");write(layouts.hostPath,layouts.host);require(widget.loadAssets(root,&error)&&widget.messages().size()==100,"reload preserves chat");widget.clearChat();require(chat->toPlainText().isEmpty()&&composer->text().isEmpty()&&widget.messages().isEmpty(),"explicit session chat reset");
    }
    auto folder=[&](const QString& name){const auto path=root+"/Interface/"+name;require(QDir().mkpath(path+"/800x600")&&image.save(path+"/800x600/Fixture 800-600.JPG","JPG"),"navigation image");return path;};
    for(const auto& entry:std::array<std::pair<QString,QString>,2>{{{"MainScreen","screen (MainMenu).cfg"},{"QuickBattleMainMenu","Screen (Quick Battle Main Menu).cfg"}}}){const auto path=folder(entry.first);QByteArray cfg("[GLOBALS]\nBackgroundFile=Fixture\n[TEXT_1]\nRect2=100,50,700,100\nText=0\n");for(int i=0;i<6;++i)cfg+=QString("[TEXTBUTTON_%1]\nRect2=150,%2,650,%3\nText=%4\n").arg(i+1).arg(200+i*50).arg(240+i*50).arg(i).toLatin1();write(path+"/"+entry.second,cfg);}
    for(bool create:{false,true}){const auto path=folder(create?"SetMultiplayerScreen":"JoinMultiplayerScreen");QByteArray cfg("[GLOBALS]\nBackgroundFile=Fixture\n");for(int i=0;i<(create?4:3);++i)cfg+=QString("[TEXT_%1]\nRect2=100,%2,700,%3\nFont=%4\nTextFlags=MIDDLE\nText=0\n").arg(i+1).arg(50+i*50).arg(90+i*50).arg(i?"SMALL":"LARGE").toLatin1();for(int i=0;i<(create?2:1);++i)cfg+=QString("[EDITBOX_%1]\nRect2=160,%2,640,%3\nFont=LARGE\n").arg(i+1).arg(210+i*50).arg(250+i*50).toLatin1();for(int i=0;i<3;++i)cfg+=QString("[RADIOBUTTON_%1]\nRect2=275,%2,700,%3\nFont=SMALL\nTextFlags=LEFT\nText=%4\n").arg(i+1).arg(330+i*30).arg(360+i*30).arg(44+i).toLatin1();cfg+="[TEXTBUTTON_1]\nRect2=75,515,275,570\nFont=LARGE\nText=10\n[TEXTBUTTON_2]\nRect2=525,515,725,570\nFont=LARGE\nText=11\n";write(path+(create?"/Screen (Set Multiplayer Game).cfg":"/Screen (Join Multiplayer Game).cfg"),cfg);}
    const auto selectionPath=folder("MultiplayerGameSelect");write(selectionPath+"/Screen (Multiplayer Game Selection).cfg","[GLOBALS]\nBackgroundFile=Fixture\n[TEXT_1]\nRect2=100,82,700,132\nFont=LARGE\nTextFlags=MIDDLE\nText=66\n[LISTBOX_1]\nRect2=165,175,635,445\nFont=SMALL\n[TEXTBUTTON_1]\nRect2=75,475,275,525\nFont=LARGE\nText=10\n[TEXTBUTTON_2]\nRect2=525,475,725,525\nFont=LARGE\nText=11\n");
    const auto mapPath=folder("MapSelectionScreen");const QByteArray mapLayout("[GLOBALS]\nBackgroundFile=Fixture\n[TEXT_1]\nRect2=234,62,568,115\nFont=LARGE\nTextFlags=CENTRE\nText=66\n[LISTBOX_1]\nRect2=165,178,635,448\nFont=SMALL\n[TEXTBUTTON_1]\nRect2=70,530,220,580\nFont=LARGE\nText=10\n[TEXTBUTTON_2]\nRect2=580,530,730,580\nFont=LARGE\nText=11\n");write(mapPath+"/screen (Map Selection Screen).cfg",mapLayout);
    MenuPreview preview;QString error;require(preview.loadAssets(root,true,&error)&&preview.openMultiplayerLobby(root,MultiplayerLobbyWidget::Mode::Host,&error),"standalone host lobby and caller");preview.show();app.processEvents();auto* stack=preview.findChild<QStackedWidget*>();auto* host=qobject_cast<MultiplayerLobbyWidget*>(stack->currentWidget());require(host&&host->lobby().gameName=="Sample game","host form context");
    host->findChild<QSlider*>("multiplayerLobbySlider1")->setValue(150);host->findChild<QPushButton*>("multiplayerLobbyMap")->click();auto* maps=qobject_cast<MapSelectionWidget*>(stack->currentWidget());require(maps&&maps->selectedMapId()=="sample-forest","host map route");maps->findChild<QListWidget*>("mapSelectionList")->setCurrentRow(1);maps->findChild<QPushButton*>("mapSelectionOk")->click();require(stack->currentWidget()==host&&host->lobby().mapId=="sample-plains"&&host->lobby().values[0]==150&&host->findChild<QPushButton*>("multiplayerLobbyMap")->hasFocus(),"Map returns host retaining edits");host->findChild<QPushButton*>("multiplayerLobbyMap")->click();maps->findChild<QListWidget*>("mapSelectionList")->setCurrentRow(2);maps->findChild<QPushButton*>("mapSelectionCancel")->click();require(host->lobby().mapId=="sample-plains","Map Cancel retains host map");
    auto* composer=host->findChild<QLineEdit*>("multiplayerLobbyComposer");composer->setText("local only");QApplication::sendEvent(composer,&enter);require(host->messages().back().text=="local only"&&preview.statusBar()->currentMessage().contains("Local chat echo"),"preview chat echo");composer->setText("unsent draft");host->findChild<QPushButton*>("multiplayerLobbyStart")->click();require(stack->currentWidget()==host&&preview.statusBar()->currentMessage().contains("adapter pending"),"host Start stays pending");host->findChild<QPushButton*>("multiplayerLobbyCancel")->click();auto* form=qobject_cast<MultiplayerSetupWidget*>(stack->currentWidget());require(form&&form->mode()==MultiplayerSetupWidget::Mode::Create&&form->findChild<QPushButton*>("multiplayerOk")->hasFocus(),"host Cancel returns Create focus");form->findChild<QPushButton*>("multiplayerOk")->click();require(stack->currentWidget()==host&&host->lobby().values[0]==150&&composer->text()=="unsent draft"&&host->messages().back().text=="local only","same host context retains draft and chat");
    host->findChild<QPushButton*>("multiplayerLobbyCancel")->click();form->findChild<QLineEdit*>("multiplayerEdit1")->setText("Different game");form->findChild<QPushButton*>("multiplayerOk")->click();require(host->lobby().gameName=="Different game"&&host->lobby().values[0]==50&&host->messages().size()==1&&composer->text().isEmpty(),"new context resets lobby and chat");
    require(preview.openMultiplayerLobby(root,MultiplayerLobbyWidget::Mode::Join,&error),"standalone guest route");auto* guest=qobject_cast<MultiplayerLobbyWidget*>(stack->currentWidget());require(guest&&guest!=host&&guest->lobby().localSlot==1&&!guest->lobby().localReady,"separate guest lobby");guest->findChild<QPushButton*>("multiplayerLobbyStart")->click();require(guest->lobby().localReady&&preview.statusBar()->currentMessage().contains("Ready accepted locally"),"guest local Ready");guest->findChild<QPushButton*>("multiplayerLobbyCancel")->click();auto* selection=qobject_cast<MultiplayerGameSelectionWidget*>(stack->currentWidget());require(selection,"guest Cancel returns selection");selection->findChild<QListWidget*>("multiplayerGameSelectionList")->setCurrentRow(0);selection->findChild<QPushButton*>("multiplayerGameSelectionOk")->click();require(stack->currentWidget()==guest&&guest->lobby().localReady,"same guest context retains Ready");guest->findChild<QPushButton*>("multiplayerLobbyCancel")->click();selection->findChild<QListWidget*>("multiplayerGameSelectionList")->setCurrentRow(1);selection->findChild<QPushButton*>("multiplayerGameSelectionOk")->click();require(guest->lobby().sessionId=="sample-island"&&!guest->lobby().localReady&&guest->messages().size()==1,"different session resets guest state");
    guest->findChild<QPushButton*>("multiplayerLobbyCancel")->click();write(layouts.joinPath,"bad layout");selection->findChild<QPushButton*>("multiplayerGameSelectionOk")->click();require(stack->currentWidget()==selection&&preview.statusBar()->currentMessage().contains("failed"),"failed guest assets preserve caller");write(layouts.joinPath,layouts.join);
    require(preview.openMultiplayer(root,MultiplayerSetupWidget::Mode::Create,&error),"reopen Create");write(layouts.hostPath,"bad layout");form->findChild<QPushButton*>("multiplayerOk")->click();require(stack->currentWidget()==form&&form->form().gameName=="Different game"&&preview.statusBar()->currentMessage().contains("failed"),"failed host assets preserve Create draft");return 0;
 }catch(const std::exception& failure){std::fprintf(stderr,"Multiplayer lobby test: %s\n",failure.what());return 1;}
}
