#include "realm_viewer_widget.hpp"
#include "realm_viewer_assets.hpp"
#include "realm-viewer-fixtures.hpp"
#include "grimoire-fixtures.hpp"
#include "menu_preview.hpp"
#include "main_menu_widget.hpp"
#include <QApplication>
#include <QKeyEvent>
#include <QLabel>
#include <QMouseEvent>
#include <QRadioButton>
#include <QStackedWidget>
#include <QStatusBar>
#include <QTemporaryDir>
#include <cstdio>
static void require(bool ok,const char* why){if(!ok)throw std::runtime_error(why);}
int main(int argc,char**argv){QApplication app(argc,argv);try{
 QTemporaryDir temp;require(temp.isValid(),"temporary root");const auto root=temp.path();realm_viewer_fixture::create(root);const auto catalog=mnm::ui::loadRealmCatalog(root);require(catalog[0].size()==8&&catalog[1].size()==12&&catalog[2].size()==16&&catalog[0][0].name=="Celtic region 1"&&catalog[0][0].flagPosition==QPoint(125,148),"bounded installed catalog metadata");
 RealmViewerWidget widget;QString error;require(widget.loadAssets(root,&error)&&error.isEmpty(),"map/sprite/config loading");widget.show();app.processEvents();auto button=[&](const QString& name){auto* b=widget.findChild<QPushButton*>(name);require(b,"button exists");return b;};require(!button("realmViewerEnter")->isEnabled()&&!button("realmViewerAuxiliary0")->isEnabled(),"empty request guards");
 RealmViewerWidget::Campaign campaign;campaign.id="opaque-campaign";campaign.name="Campaign";
 for(int r=0;r<3;++r)for(int n=0;n<2;++n)campaign.regions[r].push_back({QString("id-%1-%2").arg(r).arg(n),QString("<b>Region %1</b>").arg(n),n+1,{100+n*100,150+r*50},n?88:0,n==0,{true,true,true}});
 require(widget.setCampaign(campaign,&error)&&widget.campaign().selectedRegionIds[0]=="id-0-0","caller model and default selection");widget.focusFirstControl();require(button("realmViewerRegion0")->hasFocus()&&button("realmViewerEnter")->isEnabled(),"selected region focus");
 require(widget.findChild<QLabel*>("realmViewerHeading")->textFormat()==Qt::PlainText&&button("realmViewerRegion0")->accessibleName()=="<b>Region 0</b>","plain supplied labels");
 int requests=0,selections=0,realms=0,aux=0,cancels=0;RealmViewerWidget::Request request;
 QObject::connect(&widget,&RealmViewerWidget::regionRequested,&widget,[&](const auto& value){++requests;request=value;});QObject::connect(&widget,&RealmViewerWidget::selectionChanged,&widget,[&](const auto&){++selections;});QObject::connect(&widget,&RealmViewerWidget::realmChanged,&widget,[&](auto){++realms;});QObject::connect(&widget,&RealmViewerWidget::auxiliaryRequested,&widget,[&](auto){++aux;});QObject::connect(&widget,&RealmViewerWidget::cancelled,&widget,[&]{++cancels;});
 QKeyEvent enter(QEvent::KeyPress,Qt::Key_Return,Qt::NoModifier),repeat(QEvent::KeyPress,Qt::Key_Return,Qt::NoModifier,{},true),escape(QEvent::KeyPress,Qt::Key_Escape,Qt::NoModifier);
 button("realmViewerRegion1")->click();require(selections==1&&!button("realmViewerEnter")->isEnabled()&&button("realmViewerRegion1")->toolTip().contains("unavailable"),"unavailable selectable for inspection");QApplication::sendEvent(button("realmViewerRegion1"),&enter);require(requests==0,"unavailable request guard");
 QApplication::sendEvent(button("realmViewerRegion0"),&enter);QApplication::sendEvent(button("realmViewerRegion0"),&repeat);require(requests==1&&request.campaignId=="opaque-campaign"&&request.regionId=="id-0-0"&&request.artworkNumber==1,"typed region Enter and repeat suppression");
 QMouseEvent dbl(QEvent::MouseButtonDblClick,QPointF(5,5),QPointF(5,5),Qt::LeftButton,Qt::LeftButton,Qt::NoModifier);QApplication::sendEvent(button("realmViewerRegion0"),&dbl);require(requests==2,"double-click region activation");
 for(int r=0;r<3;++r){button(QString("realmViewerRealm%1").arg(r))->click();require(int(widget.campaign().realm)==r&&button(QString("realmViewerRealm%1").arg(r))->isChecked(),"all realm selection controls");button("realmViewerEnter")->click();require(int(request.realm)==r,"correct request realm");require(widget.selectRegion(QString("id-%1-1").arg(r),&error),"remember per-realm selection");}
 require(realms==2&&widget.selectRealm(RealmViewerWidget::Realm::Celtic,&error)&&widget.campaign().selectedRegionIds[0]=="id-0-1","switch preserves each selection");
 for(int a=0;a<4;++a){button(QString("realmViewerAuxiliary%1").arg(a))->click();}require(aux==4,"auxiliary semantic actions");QApplication::sendEvent(button("realmViewerRegion0"),&escape);require(cancels==1,"Escape closes from region");
 require(!widget.selectRealm(RealmViewerWidget::Realm(3),&error)&&!widget.selectRegion("id-2-0",&error)&&widget.campaign().realm==RealmViewerWidget::Realm::Celtic,"invalid selection transactional");
 for(int kind=0;kind<9;++kind){auto bad=campaign;switch(kind){case 0:bad.id.clear();break;case 1:bad.realm=RealmViewerWidget::Realm(3);break;case 2:bad.regions[1][0].id=bad.regions[0][0].id;break;case 3:bad.regions[0][0].flagPosition={753,150};break;case 4:bad.regions[0][0].flagArtworkIndex=89;break;case 5:bad.regions[0][0].artworkNumber=9;break;case 6:bad.selectedRegionIds[0]="missing";break;case 7:bad.regions[0][0].name="line\nbreak";break;case 8:bad.realmAvailable[0]=false;break;}require(!widget.setCampaign(bad,&error)&&widget.campaign().selectedRegionIds[0]=="id-0-1","invalid model preserves selection");}
 auto restricted=campaign;restricted.realmAvailable[1]=false;restricted.auxiliaryAvailable[0]=false;require(widget.setCampaign(restricted,&error)&&!button("realmViewerRealm1")->isEnabled()&&!button("realmViewerAuxiliary0")->isEnabled()&&!widget.selectRealm(RealmViewerWidget::Realm::Greek,&error),"caller availability enforced");
 const auto map=root+"/Interface/RealmViewer/800x600/Greek_Map.bmp";realm_viewer_fixture::write(map,"bad BMP");require(!widget.loadAssets(root,&error)&&widget.campaign().id==restricted.id,"asset rejection transactional");realm_viewer_fixture::create(root);menu_sprite_fixture::write(root,"Interface/RealmViewer/Generic/flags.spr",88);require(!widget.loadAssets(root,&error),"sprite count rejection");realm_viewer_fixture::create(root);
 const auto name=root+"/Interface/RealmViewer/Generic/Celtic_Region_01.txt";realm_viewer_fixture::write(name,QByteArray(1025,'x'));bool rejected=false;try{mnm::ui::loadRealmCatalog(root);}catch(const std::exception&){rejected=true;}require(rejected,"bounded region title read");realm_viewer_fixture::create(root);
 require(widget.loadAssets(root,&error)&&widget.setCampaign(campaign,&error),"restore assets/model");widget.resize(1200,600);app.processEvents();require(widget.contentRect()==QRect(200,0,800,600)&&button("realmViewerRegion0")->geometry()==QRect(300,150,48,52),"wide control positioning");const auto capture=widget.grab().toImage();require(capture.pixelColor(10,10)==QColor(Qt::black)&&capture.pixelColor(600,400)==QColor(80,100,120),"native map and letterbox");widget.resize(400,600);app.processEvents();require(button("realmViewerRegion0")->geometry()==QRect(50,225,24,26),"scaled flag placement");
    require(QDir().mkpath(root+"/CFG"),"strings dir");QByteArray strings("[STRINGS]\n");for(int i=0;i<100;++i)strings+=QString("STR_%1=Label %2\n").arg(i,2,10,QLatin1Char('0')).arg(i).toLatin1();grimoire_fixture::write(root+"/CFG/interface screens text.cfg",strings);menu_sprite_fixture::shared(root);
    QImage image(800,600,QImage::Format_RGB888);image.fill(QColor(90,120,150));
    for(const auto& dir:{QString("MainScreen"),QString("QuickBattleMainMenu"),QString("RegionEntry")})require(QDir().mkpath(root+"/Interface/"+dir+"/800x600"),"menu folders");
    for(const auto& dir:{QString("MainScreen"),QString("QuickBattleMainMenu")}){require(image.save(root+"/Interface/"+dir+"/800x600/Fixture 800-600.JPG","JPG"),"menu art");QByteArray cfg("[GLOBALS]\nBackgroundFile=Fixture\n[TEXT_1]\nRect2=100,50,700,100\nText=0\n");for(int i=0;i<6;++i)cfg+=QString("[TEXTBUTTON_%1]\nRect2=150,%2,650,%3\nText=%4\n").arg(i+1).arg(200+i*50).arg(240+i*50).arg(i).toLatin1();grimoire_fixture::write(root+"/Interface/"+dir+"/"+(dir=="MainScreen"?"screen (MainMenu).cfg":"Screen (Quick Battle Main Menu).cfg"),cfg);}
    require(image.save(root+"/Interface/RegionEntry/800x600/Celtic_Region_01.JPG","JPG"),"region art");QByteArray regionCfg("[TEXT_1]\nFont=LARGE\nTextFlags=LEFT\nRect2=50,40,525,75\nText=Region\n[TEXTBUTTON_1]\nFont=LARGE\nRect2=50,510,325,560\nText=78\n[TEXTBUTTON_2]\nFont=LARGE\nRect2=475,510,750,560\nText=11\n");for(int i=0;i<4;++i)regionCfg+=QString("[RADIOBUTTON_%1]\nFont=SMALL\nRect2=%2,90,%3,115\nText=%4\n").arg(i+1).arg(50+i*175).arg(225+i*175).arg(79+i).toLatin1();const std::array<int,3> first{3,6,0};for(int i=0;i<3;++i)regionCfg+=QString("[STANDARDBUTTON_%1]\nRect2=%2,25,%3,85\nSpriteIndexes=%4,%5,%6\n").arg(i+1).arg(585+i*65).arg(645+i*65).arg(first[i]).arg(first[i]+1).arg(first[i]+2).toLatin1();grimoire_fixture::write(root+"/Interface/RegionEntry/screen (Region Entry).cfg",regionCfg);
    // Original menu inputs are all synthetic, including every Region Entry art.
    const std::array<QString,3> realmNames{"Celtic","Greek","Medieval"};const std::array<int,3> counts{8,12,16};
    for(int r=0;r<3;++r)for(int n=1;n<=counts[r];++n)require(image.save(root+QString("/Interface/RegionEntry/800x600/%1_Region_%2.JPG").arg(realmNames[r]).arg(n,2,10,QLatin1Char('0')),"JPG"),"all region artwork fixtures");
    grimoire_fixture::create(root);
    widget.hide();MenuPreview preview;require(preview.loadAssets(root,false,&error),"preview menus");preview.show();app.processEvents();auto* main=preview.findChild<MainMenuWidget*>();main->findChild<QPushButton*>("mainMenuAction0")->click();auto* viewer=preview.findChild<RealmViewerWidget*>();auto* stack=preview.findChild<QStackedWidget*>();require(viewer&&stack->currentWidget()==viewer&&viewer->campaign().regions[2].size()==16,"New Game opens installed-metadata sample campaign");
    viewer->findChild<QPushButton*>("realmViewerRegion1")->click();viewer->findChild<QPushButton*>("realmViewerEnter")->click();auto* entry=preview.findChild<RegionEntryWidget*>();require(stack->currentWidget()==entry&&entry->region().id=="sample-celtic-region-2"&&entry->region().artworkNumber==2,"selected stable region reaches Entry");entry->findChild<QRadioButton*>("regionEntryDifficulty3")->click();entry->findChild<QPushButton*>("regionEntryAuxiliary0")->click();auto* book=preview.findChild<GrimoireWidget*>();require(stack->currentWidget()==book,"nested auxiliary from Entry");book->findChild<QPushButton*>("grimoireClose")->click();require(stack->currentWidget()==entry,"nested auxiliary returns Entry");entry->findChild<QPushButton*>("regionEntryCancel")->click();require(stack->currentWidget()==viewer&&viewer->campaign().selectedRegionIds[0]=="sample-celtic-region-2"&&viewer->findChild<QPushButton*>("realmViewerRegion1")->hasFocus(),"Entry Cancel restores map and flag focus");viewer->findChild<QPushButton*>("realmViewerEnter")->click();require(entry->region().difficulty==RegionEntryWidget::Difficulty::Wizard,"difficulty survives selected region reopen");entry->findChild<QPushButton*>("regionEntryCancel")->click();
    const auto firstCampaign=viewer->campaign();auto anotherCampaign=firstCampaign;anotherCampaign.id="another-campaign";require(viewer->setCampaign(anotherCampaign,&error),"second campaign snapshot");viewer->findChild<QPushButton*>("realmViewerEnter")->click();require(entry->region().difficulty==RegionEntryWidget::Difficulty::Initiate,"difficulty does not leak between campaigns sharing region IDs");entry->findChild<QPushButton*>("regionEntryCancel")->click();require(viewer->setCampaign(firstCampaign,&error),"restore first campaign");viewer->findChild<QPushButton*>("realmViewerEnter")->click();require(entry->region().difficulty==RegionEntryWidget::Difficulty::Wizard,"first campaign retains its own difficulty");entry->findChild<QPushButton*>("regionEntryCancel")->click();
    viewer->findChild<QPushButton*>("realmViewerAuxiliary1")->click();require(stack->currentWidget()==book,"direct map Grimoire");book->findChild<QPushButton*>("grimoireClose")->click();require(stack->currentWidget()==viewer&&viewer->findChild<QPushButton*>("realmViewerAuxiliary1")->hasFocus(),"direct Grimoire returns map icon");
    viewer->findChild<QPushButton*>("realmViewerRegion0")->click();viewer->findChild<QPushButton*>("realmViewerEnter")->click();require(entry->region().difficulty==RegionEntryWidget::Difficulty::Initiate,"difficulty is per-region");entry->findChild<QPushButton*>("regionEntryCancel")->click();
    viewer->findChild<QPushButton*>("realmViewerRealm2")->click();viewer->findChild<QPushButton*>("realmViewerRegion15")->click();viewer->findChild<QPushButton*>("realmViewerEnter")->click();require(entry->region().artworkRealm==RegionEntryWidget::Realm::Medieval&&entry->region().artworkNumber==16&&entry->region().name=="Medieval region 16","realm-specific art boundary");entry->findChild<QPushButton*>("regionEntryCancel")->click();
    viewer->findChild<QPushButton*>("realmViewerRegion0")->click();realm_viewer_fixture::write(root+"/Interface/RegionEntry/800x600/Medieval_Region_01.JPG","bad JPEG");viewer->findChild<QPushButton*>("realmViewerEnter")->click();require(stack->currentWidget()==viewer&&entry->region().artworkNumber==16&&preview.statusBar()->currentMessage().contains("failed"),"failed selected artwork keeps caller and previous Entry model");
    viewer->findChild<QPushButton*>("realmViewerCancel")->click();require(stack->currentWidget()==main&&main->findChild<QPushButton*>("mainMenuAction0")->hasFocus(),"map Cancel returns Main");require(preview.openRegionEntry(root,&error),"standalone Entry retained");entry->findChild<QPushButton*>("regionEntryCancel")->click();require(stack->currentWidget()==main,"standalone Entry does not return stale map");
    realm_viewer_fixture::write(root+"/Interface/RealmViewer/800x600/Celtic_Map.bmp","bad BMP");require(!preview.openRealmViewer(root,&error)&&stack->currentWidget()==main&&viewer->campaign().realm==RealmViewerWidget::Realm::Medieval,"map reopening failure preserves caller and state");return 0;
}catch(const std::exception& e){fprintf(stderr,"Realm Viewer test: %s\n",e.what());return 1;}}
