#include "region_entry_widget.hpp"
#include "menu_assets.hpp"
#include "menu_preview.hpp"
#include "main_menu_widget.hpp"
#include <QApplication>
#include <QButtonGroup>
#include <QDir>
#include <QFile>
#include <QKeyEvent>
#include <QLabel>
#include <QPushButton>
#include <QRadioButton>
#include <QStackedWidget>
#include <QStatusBar>
#include <QTemporaryDir>
#include <cstdio>
#include <stdexcept>
static void require(bool ok,const char* why){if(!ok)throw std::runtime_error(why);}
static void write(const QString& path,const QByteArray& bytes){QFile file(path);require(file.open(QIODevice::WriteOnly)&&file.write(bytes)==bytes.size(),"fixture write");}
int main(int argc,char**argv) {
 QApplication app(argc,argv);
 try {
    QTemporaryDir temporary;require(temporary.isValid(),"temporary root");const auto root=temporary.path();const auto folder=root+"/Interface/RegionEntry";
    require(QDir().mkpath(root+"/CFG")&&QDir().mkpath(folder+"/800x600"),"fixture directories");
    write(root+"/CFG/interface screens text.cfg","[STRINGS]\nSTR_00=Main\nSTR_01=Main\nSTR_02=Main\nSTR_03=Main\nSTR_04=Main\nSTR_05=Main\nSTR_11=Cancel\nSTR_78=Enter Region\nSTR_79=Initiate\nSTR_80=Apprentice\nSTR_81=Adept\nSTR_82=Wizard\n");
    const QByteArray layout("[GLOBAL]\n[TEXTBUTTON_1]\nFont=LARGE\nRect2=50,510,325,560\nText=78\n[TEXTBUTTON_2]\nFont=LARGE\nRect2=475,510,750,560\nText=11\n[STANDARDBUTTON_1]\nRect2=650,25,710,85\nSpriteIndexes=3,4,5\n[STANDARDBUTTON_2]\nRect2=715,25,775,85\nSpriteIndexes=6,7,8\n[STANDARDBUTTON_3]\nRect2=585,25,645,85\nSpriteIndexes=0,1,2\n[RADIOBUTTON_1]\nFont=SMALL\nRect2=50,90,225,115\nText=79\n[RADIOBUTTON_2]\nFont=SMALL\nRect2=225,90,400,115\nText=80\n[RADIOBUTTON_3]\nFont=SMALL\nRect2=400,90,575,115\nText=81\n[RADIOBUTTON_4]\nFont=SMALL\nRect2=575,90,750,115\nText=82\n[TEXT_1]\nFont=LARGE\nTextFlags=LEFT\nRect2=50,40,525,75\nText=Current Region\n");
    const auto config=folder+"/screen (Region Entry).cfg";write(config,layout);
    QImage celtic(800,600,QImage::Format_RGB32);celtic.fill(QColor(90,120,150));QImage greek(800,600,QImage::Format_RGB32);greek.fill(QColor(180,110,70));QImage medieval(800,600,QImage::Format_RGB32);medieval.fill(QColor(70,150,90));
    require(celtic.save(folder+"/800x600/Celtic_Region_01.JPG","JPG")&&greek.save(folder+"/800x600/Greek_Region_12.JPG","JPG")&&medieval.save(folder+"/800x600/Medieval_Region_16.JPG","JPG"),"realm artwork fixtures");
    RegionEntryWidget widget;QString error;require(widget.loadAssets(root,&error)&&error.isEmpty(),"dynamic filename with no configured background");widget.show();app.processEvents();
    auto* enter=widget.findChild<QPushButton*>("regionEntryEnter");auto* cancel=widget.findChild<QPushButton*>("regionEntryCancel");auto* heading=widget.findChild<QLabel*>("regionEntryHeading");
    auto radio=[&](int i){return widget.findChild<QRadioButton*>(QString("regionEntryDifficulty%1").arg(i));};auto auxiliary=[&](int i){return widget.findChild<QPushButton*>(QString("regionEntryAuxiliary%1").arg(i));};
    require(!enter->isEnabled()&&!auxiliary(0)->isEnabled()&&heading->text()=="Current Region"&&radio(0)->isChecked()&&enter->text()=="Enter Region"&&cancel->text()=="Cancel","empty region guards and static labels");
    int entered=0,cancelled=0,auxCount=0;RegionEntryWidget::Request request;RegionEntryWidget::AuxiliaryAction action=RegionEntryWidget::AuxiliaryAction::Character;
    QObject::connect(&widget,&RegionEntryWidget::enterRequested,&widget,[&](const auto& value){++entered;request=value;});QObject::connect(&widget,&RegionEntryWidget::cancelled,&widget,[&]{++cancelled;});QObject::connect(&widget,&RegionEntryWidget::auxiliaryRequested,&widget,[&](auto value){++auxCount;action=value;});
    QKeyEvent keyEnter(QEvent::KeyPress,Qt::Key_Return,Qt::NoModifier),repeat(QEvent::KeyPress,Qt::Key_Return,Qt::NoModifier,QString(),true),escape(QEvent::KeyPress,Qt::Key_Escape,Qt::NoModifier);
    QApplication::sendEvent(radio(0),&keyEnter);require(entered==0,"empty Enter guarded");
    RegionEntryWidget::Region region;region.id="opaque-region";region.name="<b>Region name</b>";require(widget.setRegion(region,&error)&&heading->text()==region.name&&heading->textFormat()==Qt::PlainText&&enter->isEnabled(),"caller identity and plain-text region title");
    for(int i=0;i<4;++i){radio(i)->click();enter->click();require(entered==i+1&&request.regionId=="opaque-region"&&int(request.difficulty)==i&&int(widget.region().difficulty)==i,"all typed difficulty requests");int checked=0;for(int j=0;j<4;++j)checked+=radio(j)->isChecked();require(checked==1,"exclusive difficulty");}
    require(radio(0)->text()=="Initiate"&&radio(3)->text()=="Wizard","installed radio labels");
    widget.focusFirstControl();require(radio(3)->hasFocus(),"focus selected difficulty");QApplication::sendEvent(radio(3),&keyEnter);require(entered==5,"Enter from radio once");QApplication::sendEvent(radio(3),&repeat);require(entered==5,"Enter repeat suppressed");
    for(int i=0;i<3;++i){QApplication::sendEvent(auxiliary(i),&keyEnter);require(auxCount==i+1&&int(action)==i&&entered==5,"focused auxiliary semantic action");}
    require(auxiliary(0)->accessibleName()=="Grimoire"&&auxiliary(1)->toolTip()=="Spellbox"&&auxiliary(2)->accessibleName()=="Character","text icon accessibility");
    auto unavailable=widget.region();unavailable.enterAvailable=false;unavailable.auxiliaryAvailable[1]=false;require(widget.setRegion(unavailable),"availability update");enter->click();auxiliary(1)->click();QApplication::sendEvent(radio(0),&keyEnter);require(entered==5&&auxCount==3&&!enter->isEnabled()&&!auxiliary(1)->isEnabled()&&auxiliary(0)->isEnabled(),"caller availability guards");
    require(widget.setRegion(region),"restore region");auto invalid=region;invalid.artworkRealm=RegionEntryWidget::Realm(99);require(!widget.setRegion(invalid,&error)&&!error.isEmpty()&&widget.region().id=="opaque-region","invalid realm transactional");invalid=region;invalid.artworkNumber=9;require(!widget.setRegion(invalid,&error),"Celtic artwork range");invalid=region;invalid.difficulty=RegionEntryWidget::Difficulty(4);require(!widget.setRegion(invalid,&error),"invalid difficulty");invalid=region;invalid.name.clear();require(!widget.setRegion(invalid,&error),"partial region");invalid=region;invalid.name="two\nlines";require(!widget.setRegion(invalid,&error),"multiline heading rejected");
    auto missing=region;missing.artworkNumber=2;missing.name="Missing picture";require(!widget.setRegion(missing,&error)&&widget.region().artworkNumber==1&&heading->text()==region.name&&radio(0)->isChecked(),"missing artwork preserves all model fields");
    auto next=region;next.id="greek-opaque";next.name="Greek sample";next.artworkRealm=RegionEntryWidget::Realm::Greek;next.artworkNumber=12;next.difficulty=RegionEntryWidget::Difficulty::Adept;require(widget.setRegion(next,&error)&&radio(2)->isChecked()&&heading->text()=="Greek sample","realm-specific art and difficulty refresh");const auto greekCapture=widget.grab().toImage();require(qAbs(greekCapture.pixelColor(400,300).red()-180)<4,"Greek artwork chosen");
    next.artworkRealm=RegionEntryWidget::Realm::Medieval;next.artworkNumber=16;require(widget.setRegion(next,&error)&&qAbs(widget.grab().toImage().pixelColor(400,300).green()-150)<4,"Medieval artwork upper bound");next.artworkNumber=17;require(!widget.setRegion(next,&error)&&widget.region().artworkNumber==16,"Medieval artwork range rejected");
    write(config,QByteArray(layout).replace("SpriteIndexes=3,4,5","SpriteIndexes=6,7,8"));require(!widget.loadAssets(root,&error)&&widget.region().artworkNumber==16&&radio(2)->isChecked()&&enter->text()=="Enter Region","icon role rejection transactional");write(config,QByteArray(layout).replace("50,40,525,75","50,40,900,75"));require(!widget.loadAssets(root,&error),"invalid geometry rejected");write(config,layout);require(widget.loadAssets(root,&error)&&radio(2)->isChecked(),"reload retains selected difficulty");
    QApplication::sendEvent(radio(2),&escape);QApplication::sendEvent(cancel,&keyEnter);require(cancelled==2&&entered==5,"Escape and focused Cancel");
    require(widget.setRegion(region),"Celtic restore");widget.resize(1200,600);app.processEvents();require(widget.contentRect()==QRect(200,0,800,600)&&enter->geometry()==QRect(250,510,275,50)&&auxiliary(2)->geometry()==QRect(785,25,60,60),"wide layout");const auto capture=widget.grab().toImage();require(capture.pixelColor(10,10)==QColor(Qt::black)&&qAbs(capture.pixelColor(600,300).blue()-150)<4,"background and letterbox");widget.resize(400,600);app.processEvents();require(radio(0)->geometry()==QRect(25,195,88,13)&&enter->geometry()==QRect(25,405,138,25),"scaled geometry");
    for(const auto& name:{QString("../Celtic_Region_01.JPG"),QString("/Celtic_Region_01.JPG"),QString("C:\\image.JPG")}){bool rejected=false;try{mnm::ui::loadMenuAssets(root,"Interface/RegionEntry","screen (Region Entry).cfg","JPG",QSize(800,600),QString(),name);}catch(const std::exception&){rejected=true;}require(rejected,"explicit image filename remains confined");}
    for(const auto& entry:std::array<std::pair<QString,QString>,2>{{{"MainScreen","screen (MainMenu).cfg"},{"QuickBattleMainMenu","Screen (Quick Battle Main Menu).cfg"}}}){const auto path=root+"/Interface/"+entry.first;require(QDir().mkpath(path+"/800x600")&&celtic.save(path+"/800x600/Fixture 800-600.JPG","JPG"),"navigation image");QByteArray cfg("[GLOBALS]\nBackgroundFile=Fixture\n[TEXT_1]\nRect2=100,50,700,100\nText=0\n");for(int i=0;i<6;++i)cfg+=QString("[TEXTBUTTON_%1]\nRect2=150,%2,650,%3\nText=%4\n").arg(i+1).arg(200+i*50).arg(240+i*50).arg(i).toLatin1();write(path+"/"+entry.second,cfg);}
    widget.hide();MenuPreview preview;require(preview.loadAssets(root,false,&error)&&preview.openRegionEntry(root,&error),"standalone Region Entry preview");preview.show();app.processEvents();auto* screen=preview.findChild<RegionEntryWidget*>();auto* stack=preview.findChild<QStackedWidget*>();require(stack->currentWidget()==screen&&screen->region().id=="sample-celtic-region-1","sample region supplied");screen->findChild<QRadioButton*>("regionEntryDifficulty3")->click();screen->findChild<QPushButton*>("regionEntryEnter")->click();require(stack->currentWidget()==screen&&preview.statusBar()->currentMessage().contains("Wizard")&&preview.statusBar()->currentMessage().contains("adapter pending"),"Enter remains pending with selected difficulty");screen->findChild<QPushButton*>("regionEntryAuxiliary0")->click();require(stack->currentWidget()==screen&&preview.statusBar()->currentMessage().contains("Grimoire"),"auxiliary action stays pending");screen->findChild<QPushButton*>("regionEntryCancel")->click();auto* main=preview.findChild<MainMenuWidget*>();require(stack->currentWidget()==main&&main->findChild<QPushButton*>("mainMenuAction0")->hasFocus(),"Cancel returns Main focus");require(preview.openRegionEntry(root,&error)&&screen->region().difficulty==RegionEntryWidget::Difficulty::Wizard,"reopen retains draft");screen->findChild<QPushButton*>("regionEntryCancel")->click();write(folder+"/800x600/Celtic_Region_01.JPG","bad JPEG");require(!preview.openRegionEntry(root,&error)&&stack->currentWidget()==main&&screen->region().difficulty==RegionEntryWidget::Difficulty::Wizard,"failed artwork load preserves caller and draft");return 0;
 }catch(const std::exception& failure){std::fprintf(stderr,"Region Entry test: %s\n",failure.what());return 1;}
}
