#include "surface_backend.hpp"
#include "../reconstruction/rendering/owned_surface_retry.hpp"
#include "../reconstruction/rendering/surface_bitmap.hpp"
#include <QGuiApplication>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QFile>
#include <iostream>
using namespace mnm::render;
static unsigned checks=0,refusals=0;
static void require(bool ok,const char* message){if(!ok)throw std::runtime_error(message);++checks;}
template<class F>static void refuses(F f){bool rejected=false;try{f();}catch(const std::runtime_error&){rejected=true;}require(rejected,"Expected native refusal");++refusals;}
static PixelFormat indexed{8,{}},rgb565{16,{0xf800,0x7e0,31}};
static SurfaceBackend::Palette colors(unsigned id,unsigned generation){SurfaceBackend::Palette p{};for(unsigned i=0;i<256;++i)p[i]={std::uint8_t(i*17+id*37+generation*11),std::uint8_t(i*29+3+generation*19),std::uint8_t(i*43+9+generation*23)};return p;}
static QJsonArray sample(SurfaceBackend& b,SurfaceId id){auto image=b.read(id);QJsonArray a;for(int y=0;y<6;++y)for(int x=0;x<8;++x)a.append(int(image.pixels[std::size_t(y)*image.width+x]));return a;}
static QJsonArray palette(SurfaceBackend& b,SurfaceId id){std::uint32_t dc=0;require(b.acquireDc(id,dc)==0,"Acquire palette lease");QJsonArray a;for(auto c:b.dcPalette(id))a.append(int(c.red)|(int(c.green)<<8)|(int(c.blue)<<16));require(b.releaseDc(id,dc)==0,"Release palette lease");return a;}
static QJsonObject ownership(SurfaceBackend& b){SurfaceBackend::Palette defaults{};const auto a=b.createPalette(colors(0,0)),p=b.createPalette(colors(1,0));auto s0=b.create({8,6,std::vector<std::uint32_t>(48,0x12)},indexed,0x840,defaults),s1=b.create({8,6,std::vector<std::uint32_t>(48,0x23)},indexed,0x840,defaults);b.bindPaletteObject(s0,a);b.bindPaletteObject(s1,a);b.setSourceKey(s0,0x35);b.setSourceKey(s1,0x46);
 // Palette aliases persist after their caller's final release and through detach.
 const auto alias=b.alias(s0);require(alias==s0,"Canonical surface alias");require(b.release(s0)==1,"Surface held by alias");QJsonArray pixels{sample(b,alias)};b.setSourceKey(alias,0x57);require(b.sourceKey(alias)==0x57,"Key update through alias");require(b.releasePalette(a)==0,"Drop caller palette");refuses([&]{b.updatePaletteObject(a,0,{{1,2,3}});});SurfaceBackend::PaletteId retained=0;require(!b.getPaletteObject(s1,retained)&&retained==a,"Recover retained palette identity");auto updates=colors(0,1);b.updatePaletteObject(retained,37,{updates.begin()+37,updates.begin()+44});QJsonArray tables{palette(b,alias),palette(b,s1)};pixels.append(sample(b,alias));pixels.append(sample(b,s1));b.bindPaletteObject(alias,std::nullopt);SurfaceBackend::PaletteId sentinel=0xabababab;const auto detached=b.getPaletteObject(alias,sentinel);require(sentinel==0xabababab,"Missing palette output retained");tables.append(palette(b,s1));require(b.releasePalette(retained)==0,"Release recovered palette");require(b.release(alias)==0,"Final alias release");refuses([&]{b.read(alias);});b.bindPaletteObject(s1,p);tables.append(palette(b,s1));pixels.append(sample(b,s1));b.destroy(s1);require(b.paletteObjects()==1,"Only caller B palette remains");
 // Attachment holds a back buffer after all external references are returned.
 auto front=b.create({640,480,std::vector<std::uint32_t>(640*480,0x31)},indexed,0x40,defaults,true),back=b.create({640,480,std::vector<std::uint32_t>(640*480,0xa5)},indexed,0x40,defaults);b.bindPaletteObject(front,p);b.bindPaletteObject(back,p);b.attachBackBuffer(front,back);b.setSourceKey(front,0x61);b.setSourceKey(back,0x72);auto fa=b.alias(front),ba=b.alias(back);QJsonArray flips;
 for(unsigned phase=0;phase<4;++phase){const auto before=b.stats();const auto h=b.flip(front);const auto after=b.stats();require(before.uploads==after.uploads&&before.nativeReadbacks==after.nativeReadbacks,"Resident flip transfers");require(b.sourceKey(fa)==0x61&&b.sourceKey(ba)==0x72,"Flip preserves object keys");flips.append(QJsonObject{{"front_key",int(*b.sourceKey(fa))},{"back_key",int(*b.sourceKey(ba))},{"hresult",qint64(h)},{"front",sample(b,fa)},{"back",sample(b,ba)}});}
 QJsonArray held;
 for(unsigned n=0;n<4;++n){auto id=n%2?back:front;SurfaceBackend::Descriptor descriptor{};std::uint32_t dc=0;require((n<2?b.lock(id,descriptor):b.acquireDc(id,dc))==0,"Held flip setup");const auto h=b.flip(front,0);const auto same=n<2?b.unlock(id):b.releaseDc(id,dc);auto other=n%2?front:back;const auto opposite=n<2?b.unlock(other):b.releaseDc(other,dc);std::uint32_t undo=0,returned=0;if(n>=2){undo=b.flip(front);returned=b.releaseDc(id,dc);require(!returned,"DC return after flipback");}held.append(QJsonObject{{"hresult",qint64(h)},{"same_release",qint64(same)},{"other_release",qint64(opposite)},{"undo_flip",qint64(undo)},{"returned",qint64(returned)},{"front",sample(b,front)},{"back",sample(b,back)}});}
 require(b.release(back)==1&&b.release(ba)==0,"Drop external back references");refuses([&]{b.read(back);});require(b.getBackBuffer(front)==back,"Attachment retains original identity");auto reacquired=sample(b,back);require(b.release(front)==1,"Front retained by alias");require(!b.flip(fa),"Flip surviving front alias");auto finalFront=sample(b,fa),finalBack=sample(b,back);require(b.release(back)==0&&b.release(fa)==0,"Retire attached pair");refuses([&]{b.alias(front);});refuses([&]{b.getBackBuffer(front);});require(!b.releasePalette(p)&&b.paletteObjects()==0&&b.stats().surfaces==0,"All ownership retired");auto recreated=b.create({1,1,{7}},rgb565);require(recreated!=s0&&recreated!=front&&recreated!=back,"Identity recreation");b.destroy(recreated);
 return {{"pixels",pixels},{"palettes",tables},{"detached_status",qint64(detached)},{"flips",flips},{"held",held},{"reacquired",reacquired},{"final_front",finalFront},{"final_back",finalBack}};
}
static QJsonArray driverRecovery(SurfaceBackend& b){
 SurfaceBackend::Palette defaults{};auto a=b.createPalette(colors(0,0)),c=b.createPalette(colors(1,0));std::vector<SurfaceId> ids;
 for(unsigned n=0;n<4;++n){const int w=n==3?640:8,h=n==3?480:6;auto id=b.create({w,h,std::vector<std::uint32_t>(std::size_t(w)*h,0x12)},indexed,n?0x40:0x840,defaults,n==3);b.bindPaletteObject(id,n==2?c:a);b.setSourceKey(id,0x35);ids.push_back(id);}
 QJsonArray states;
 const auto record=[&](unsigned phase,unsigned n,bool known){auto id=ids[n];SurfaceBackend::PaletteId got=0xabababab;const auto h=b.getPaletteObject(id,got);QJsonObject out{{"phase",int(phase)},{"surface",int(n)},{"lost",qint64(b.isLost(id))},{"get_palette",qint64(h)},{"key",int(*b.sourceKey(id))}};
  if(!h){require(got==(n==2||(phase==9)?c:a),"Driver palette retained identity");require(!b.releasePalette(got),"Returned palette caller cleanup");out["table"]=palette(b,id);}
  else require(got==0xabababab,"Lost palette output unchanged");
  if(known)out["indices"]=sample(b,id);else if(!b.isLost(id))refuses([&]{b.read(id);});states.append(out);
 };
 // Caller references survive the GetPalette return/release pair.
 // Drop them only after setup; bindings become the owners for reacquisition.
 require(!b.releasePalette(a)&&!b.releasePalette(c),"Bindings retain palette objects");
 for(unsigned n=0;n<4;++n)record(0,n,true);
 for(unsigned n=1;n<4;++n){b.markLost(ids[n]);}
 SurfaceBackend::PaletteId held=0;require(!b.getPaletteObject(ids[0],held)&&held==a,"Usable sibling palette during loss");auto partial=colors(0,1);b.updatePaletteObject(held,37,{partial.begin()+37,partial.begin()+44});require(!b.releasePalette(held),"Loss update caller cleanup");for(unsigned n=0;n<4;++n)record(1,n,n==0);
 b.update(ids[0],0,0,{8,6,std::vector<std::uint32_t>(48,0xab)});
 for(unsigned n=0;n<4;++n){require(b.restore(ids[n],SurfaceBackend::Mode{800,600,indexed})==(n==3?0x8876024b:0u),"Driver mode-change Restore result");record(2,n,n==0);}
 for(unsigned n=1;n<4;++n){b.markLost(ids[n]);}
 for(unsigned n=0;n<4;++n)record(3,n,n==0);
 for(unsigned n=0;n<4;++n){require(!b.restore(ids[n],SurfaceBackend::Mode{640,480,indexed}),"Driver matching Restore");record(4,n,n==0);require(!b.restore(ids[n],SurfaceBackend::Mode{640,480,indexed}),"Driver repeated Restore");record(5,n,n==0);
  int w=n==3?640:8,h=n==3?480:6;Image reload{w,h,{}};for(int y=0;y<h;++y)for(int x=0;x<w;++x)reload.pixels.push_back((unsigned(y*8+x)*37+n*11+6*13)&255);b.update(ids[n],0,0,reload);record(6,n,true);
 }
 require(!b.getPaletteObject(ids[0],a)&&!b.getPaletteObject(ids[2],c),"Full update reacquisition");auto pa=colors(0,2),pc=colors(1,2);b.updatePaletteObject(a,0,{pa.begin(),pa.end()});b.updatePaletteObject(c,0,{pc.begin(),pc.end()});require(!b.releasePalette(a)&&!b.releasePalette(c),"Full update caller cleanup");for(unsigned n=0;n<4;++n)record(8,n,true);
 require(!b.getPaletteObject(ids[2],c),"Rebind target reacquisition");b.bindPaletteObject(ids[1],c);require(!b.releasePalette(c),"Rebind caller cleanup");record(9,1,true);for(auto id:ids)b.destroy(id);require(!b.paletteObjects()&&!b.stats().surfaces,"Driver recovery cleanup");return states;
}
static void guards(SurfaceBackend& b){
 auto id=b.create({8,6,std::vector<std::uint32_t>(48,3)},rgb565);auto alias=b.alias(id);SurfaceBackend::Descriptor d{};require(!b.lock(id,d),"Alias borrow setup");require(b.release(id)==1,"Release nonfinal borrowed alias");refuses([&]{b.release(alias);});require(b.references(alias)==1&&b.borrowed(alias),"Final borrowed release retains identity");refuses([&]{b.markLost(alias);});require(!b.unlock(alias)&&!b.release(alias),"Return borrowed final alias");
 auto front=b.create({8,6,std::vector<std::uint32_t>(48,1)},rgb565),back=b.create({8,6,std::vector<std::uint32_t>(48,2)},rgb565);b.attachBackBuffer(front,back);refuses([&]{b.attachBackBuffer(back,front);});b.invalidateContents(back);require(!b.flip(front),"Undefined buffer flip");refuses([&]{b.read(front);});require(b.read(back).pixels==std::vector<std::uint32_t>(48,1),"Flip transfers validity with storage");b.markLost(front);require(b.flip(front)==0x887601c2,"Lost flip admission");require(b.read(back).pixels==std::vector<std::uint32_t>(48,1),"Lost flip preserves other storage");b.release(back);b.release(front);
 auto p=b.createPalette(colors(0,0)),s=b.create({8,6,std::vector<std::uint32_t>(48,1)},indexed,0x840,colors(1,0));b.bindPaletteObject(s,p);std::uint32_t dc=0;require(!b.acquireDc(s,dc),"Shared palette DC setup");const auto before=b.dcPalette(s);auto change=colors(0,1);b.updatePaletteObject(p,37,{change.begin()+37,change.begin()+44});require(b.dcPalette(s)[37].red==before[37].red&&b.dcPalette(s)[37].green==before[37].green&&b.dcPalette(s)[37].blue==before[37].blue,"Active DC freezes shared palette update");require(!b.releaseDc(s,dc),"Shared palette DC return");require(!b.acquireDc(s,dc)&&b.dcPalette(s)[37].red==change[37].red,"Next DC observes shared update");require(!b.releaseDc(s,dc),"Next DC cleanup");refuses([&]{b.updatePaletteObject(p,255,{{1,2,3},{4,5,6}});});b.releasePalette(p);b.destroy(s);
 // An unmatched Unlock during a DC must not migrate an unvalidated mapping.
 front=b.create({8,6,std::vector<std::uint32_t>(48,1)},rgb565);back=b.create({8,6,std::vector<std::uint32_t>(48,2)},rgb565);b.attachBackBuffer(front,back);std::uint32_t heldDc=0;require(!b.acquireDc(front,heldDc)&&!b.unlock(front),"DC zero-balance setup");const auto beforeFlip=b.stats();refuses([&]{b.flip(front);});require(b.borrowed(front)&&!b.borrowed(back)&&b.mapBalance(front)==0&&b.read(back).pixels==std::vector<std::uint32_t>(48,2)&&b.stats().uploads==beforeFlip.uploads,"Unmatched DC flip refusal preserves ownership and storage");require(!b.releaseDc(front,heldDc)&&b.poisoned(front),"Return unmatched DC leaves explicit debt");
 // Poisoned ownership retires only with the enclosing owner, as in old fixtures.
  // Foreign owners and stale IDs must refuse before changing owned state.
 SurfaceBackend other;auto foreign=other.createPalette(colors(0,0));refuses([&]{b.retainPalette(foreign);});other.releasePalette(foreign);require(!b.paletteObjects()&&b.stats().surfaces==2,"Only poisoned attachment remains for owner teardown");
}
static QJsonObject recovery(SurfaceBackend& b){using namespace mnm::reconstruction;SurfaceBackend::Palette defaults{};unsigned cases=0,pixels=0;
 // Shared palette changes through loss and Restore do not define index bytes.
 auto p=b.createPalette(colors(0,0));auto first=b.create({8,6,std::vector<std::uint32_t>(48,0x12)},indexed,0x40,defaults),second=b.create({8,6,std::vector<std::uint32_t>(48,0x23)},indexed,0x40,defaults);b.bindPaletteObject(first,p);b.bindPaletteObject(second,p);b.markLost(first);b.markLost(second);SurfaceBackend::PaletteId out=0xabababab;require(b.getPaletteObject(first,out)==0x887601c2&&out==0xabababab,"Lost GetPalette retains output");auto changed=colors(0,1);b.updatePaletteObject(p,37,{changed.begin()+37,changed.begin()+44});require(!b.restore(first)&&!b.restore(second),"Restore shared palette surfaces");refuses([&]{b.read(first);});refuses([&]{b.present(second);});b.update(first,0,0,{8,1,std::vector<std::uint32_t>(8,9)});refuses([&]{b.read(first);});b.update(first,0,0,{8,6,std::vector<std::uint32_t>(48,9)});require(b.read(first).pixels==std::vector<std::uint32_t>(48,9),"Explicit reload bytes");require(!b.restore(first)&&b.read(first).pixels==std::vector<std::uint32_t>(48,9),"Repeated healthy Restore");b.destroy(first);b.destroy(second);require(!b.releasePalette(p),"Palette recovery cleanup");
 // Primary wrong-mode failure preserves lost state and metadata.
 auto primary=b.create({8,6,std::vector<std::uint32_t>(48,1)},rgb565,0x40,std::nullopt,true);b.setSourceKey(primary,0x5678);b.markLost(primary);require(b.restore(primary,SurfaceBackend::Mode{9,6,rgb565})==0x8876024b&&b.isLost(primary)==0x887601c2,"Primary wrong-mode refusal");require(b.sourceKey(primary)==0x5678,"Lost source key retention");require(!b.restore(primary,SurfaceBackend::Mode{8,6,rgb565}),"Primary matching Restore");SurfaceBackend::Descriptor desc{};refuses([&]{b.lock(primary,desc);});b.destroy(primary);
 Image source{8,6,{}},destination{8,6,{}};for(unsigned i=0;i<48;++i){source.pixels.push_back(i%3?0x100+i:0x5678);destination.pixels.push_back(0xa000+i);}
 for(unsigned wrapper=0;wrapper<4;++wrapper)for(unsigned reloaded=0;reloaded<4;++reloaded){auto s=b.create(source,rgb565),d=b.create(destination,rgb565);b.setSourceKey(s,0x5678);b.markLost(s);b.markLost(d);unsigned sourceLoads=0,destinationLoads=0;OwnedSurfaceRetryAdapter::Callbacks cb;cb.source=[&](auto& backend,auto id){++sourceLoads;backend.update(id,0,0,source);};cb.destination=[&](auto& backend,auto id){++destinationLoads;backend.update(id,0,0,destination);};OwnedSurfaceRetryAdapter adapter(b,s,d,{0,0,8,6},{0,0,8,6},wrapper==1,cb);SurfaceRetryInput config;config.wrapper=SurfaceWrapper(wrapper);config.keyEnabled=true;config.sourceKey=0x5678;config.destinationKey=0xe123;config.color=0x1234;config.sourceReload=reloaded&1;config.destinationReload=reloaded&2;
  bool undefined=false;SurfaceRetryResult result;try{result=runSurfaceRetry(config,adapter,3);}catch(const std::runtime_error&){undefined=true;}
  if(wrapper<2){require(!undefined&&result.returned&&result.draws==(wrapper==1?2u:1u),"Fill recovery schedule");require(sourceLoads==0,"Fill restores destination only");if(wrapper==1){require(b.read(d).pixels==std::vector<std::uint32_t>(48,0x1234),"Full fill retry overwrite");pixels+=48;}else if(reloaded&2){require(b.read(d).pixels==destination.pixels,"Partial fill no post-restore retry");pixels+=48;}else refuses([&]{b.read(d);});}
  else{const bool defined=(reloaded&1)&&(wrapper==2||(reloaded&2));require(undefined!=defined,"Undefined copy recovery guard");if(defined){require(result.returned&&result.draws==2,"Copy recovery retry");auto expected=source.pixels;if(wrapper==3)for(unsigned i=0;i<48;++i)if(expected[i]==0x5678)expected[i]=destination.pixels[i];require(b.read(d).pixels==expected,"Recovered copy/keyed bytes");pixels+=48;}}
  require(b.sourceKey(d)==0xe123,"Key reapplication");b.destroy(s);b.destroy(d);++cases;
 }
 // The cursor sentinel reload targets its global resource, independently of dest.
 // A supplied 8-bit BMP follows the recovered sequential reader and DC path.
 std::vector<std::uint8_t> bmp(54+1024+48,0);
 const auto put=[&](unsigned at,std::uint32_t value){for(unsigned n=0;n<4;++n)bmp[at+n]=std::uint8_t(value>>(8*n));};
 bmp[0]='B';bmp[1]='M';put(2,unsigned(bmp.size()));put(10,54+1024);put(14,40);put(18,8);put(22,6);bmp[26]=1;bmp[28]=8;put(34,48);
 for(unsigned i=0;i<256;++i)for(unsigned channel=0;channel<3;++channel)bmp[54+4*i+channel]=std::uint8_t(i);
 for(unsigned y=0;y<6;++y)for(unsigned x=0;x<8;++x)bmp[54+1024+(5-y)*8+x]=std::uint8_t(y*8+x);
 SurfaceBackend::Palette gray{};for(unsigned i=0;i<256;++i)gray[i]={std::uint8_t(i),std::uint8_t(i),std::uint8_t(i)};
 auto cursor=b.create({8,6,std::vector<std::uint32_t>(48,255)},indexed,0x840,gray),d=b.create(destination,rgb565);b.markLost(d);OwnedSurfaceRetryAdapter::Callbacks cb;cb.cursorSurface=cursor;unsigned cursorLoads=0;
 cb.cursor=[&](auto& backend,auto id){++cursorLoads;reloadCursorBitmap([&](std::string_view path){require(path=="bitmaps\\cursors.bmp","Fixed cursor reader path");return std::optional(bmp);},[&](const DibInput& dib){std::uint32_t token=0;require(!backend.acquireDc(id,token),"Cursor DC acquire");try{backend.reloadDib(id,dib);}catch(...){backend.releaseDc(id,token);throw;}require(!backend.releaseDc(id,token),"Cursor DC return");});};
 OwnedSurfaceRetryAdapter a(b,std::nullopt,d,{},{0,0,8,6},false,cb);SurfaceRetryInput config;config.wrapper=SurfaceWrapper::PartialFill;config.destinationRoute=SurfaceReloadRoute::CursorBitmap;auto result=runSurfaceRetry(config,a,2);std::vector<std::uint32_t> expectedCursor;for(unsigned i=0;i<48;++i)expectedCursor.push_back(i);require(result.returned&&cursorLoads==1&&b.read(cursor).pixels==expectedCursor&&!b.borrowed(cursor),"Global cursor BMP DC recovery binding");refuses([&]{b.read(d);});b.destroy(d);b.destroy(cursor);

 // Finite retry exhaustion retains borrowed ownership and known bytes.
 auto s=b.create(source,rgb565);d=b.create(destination,rgb565);std::uint32_t dc=0;require(!b.acquireDc(d,dc),"Busy retry setup");OwnedSurfaceRetryAdapter::Callbacks noCallbacks;OwnedSurfaceRetryAdapter busy(b,s,d,{0,0,8,6},{0,0,8,6},false,noCallbacks);config={};config.wrapper=SurfaceWrapper::OpaqueCopy;auto bounded=runSurfaceRetry(config,busy,2);require(bounded.budgetExhausted&&!bounded.returned&&bounded.draws==2&&b.borrowed(d),"Retry budget preserves busy lease");require(!b.releaseDc(d,dc)&&b.read(d).pixels==destination.pixels,"Busy retry preserves pixels");b.destroy(s);b.destroy(d);
 // Wrong-mode Restore keeps the primary lost, including the full-fill retry.
 d=b.create(destination,rgb565,0x40,std::nullopt,true);b.markLost(d);OwnedSurfaceRetryAdapter::Callbacks mismatch;mismatch.display=SurfaceBackend::Mode{9,6,rgb565};std::vector<std::uint32_t> reports;mismatch.report=[&](auto h){reports.push_back(h);};OwnedSurfaceRetryAdapter failed(b,std::nullopt,d,{},{0,0,8,6},true,mismatch);config={};config.wrapper=SurfaceWrapper::FullFill;auto full=runSurfaceRetry(config,failed,2);require(full.returned&&full.draws==2&&b.isLost(d)==0x887601c2&&reports==std::vector<std::uint32_t>({0x887601c2,0x8876024b,0x887601c2}),"Failed primary Restore ordering/state");b.destroy(d);
 // A failed explicit reloader leaves contents unknown and propagates failure.
 s=b.create(source,rgb565);d=b.create(destination,rgb565);b.markLost(s);b.markLost(d);OwnedSurfaceRetryAdapter::Callbacks broken;broken.source=[](auto&,auto){throw std::runtime_error("Asset reload failed");};OwnedSurfaceRetryAdapter failure(b,s,d,{0,0,8,6},{0,0,8,6},false,broken);config={};config.wrapper=SurfaceWrapper::OpaqueCopy;config.sourceReload=true;refuses([&]{runSurfaceRetry(config,failure,2);});require(!b.isLost(s)&&b.isLost(d)==0x887601c2,"Reload failure stops before destination recovery");refuses([&]{b.read(s);});b.destroy(s);b.destroy(d);
 require(b.stats().surfaces==0&&b.paletteObjects()==0,"Recovery ownership cleanup");return {{"cases",int(cases)},{"pixels",int(pixels)},{"cursor_loads",int(cursorLoads)}};
}
int main(int argc,char** argv){QGuiApplication app(argc,argv);try{require(argc==2,"Output path required");{SurfaceBackend guardOwner;guards(guardOwner);}SurfaceBackend b;auto own=ownership(b),rec=recovery(b);auto driver=driverRecovery(b);QJsonObject output{{"ownership",own},{"recovery",rec},{"driver_recovery",driver},{"checks",int(checks)},{"refusals",int(refusals)}};QFile file(QString::fromLocal8Bit(argv[1]));require(file.open(QIODevice::WriteOnly|QIODevice::NewOnly),"New output");file.write(QJsonDocument(output).toJson());std::cout<<"{\"success\":true,\"checks\":"<<checks<<",\"refusals\":"<<refusals<<"}\n";return 0;}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
