#!/usr/bin/env python3
"""Generate dependency-free constants from the versioned wire schemas."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent


def validate(s):
    assert s['byte_order'] == 'little'
    assert len(s['magic'].encode('ascii')) == 8
    assert s['declared_size_kind'] in ('size', 'header_size')
    assert 16 <= s['header_size'] <= s['size']
    end = 0
    names = set()
    for f in s['fields']:
        assert f['name'] not in names
        names.add(f['name'])
        assert f['offset'] == end, 'Fields must cover the entire file without gaps or overlaps'
        assert f['size'] > 0
        assert f['owner'] in ('creator', 'producer', 'consumer')
        assert f['type'] in ('bytes', 'u32le', 'u32le_array')
        if f['type'] != 'bytes':
            assert f['offset'] % 4 == 0 and f['size'] % 4 == 0
        if f['type'] == 'u32le':
            assert f['size'] == 4
        end += f['size']
    assert end == s['size']


def constants(s):
    result = {'VERSION': s['version'], 'SIZE': s['size'],
              'HEADER_SIZE': s['header_size'],
              'DECLARED_SIZE': s[s['declared_size_kind']]}
    for f in s['fields']:
        result[f"{f['name'].upper()}_OFFSET"] = f['offset']
        result[f"{f['name'].upper()}_SIZE"] = f['size']
    for name, value in s['constants'].items():
        assert name.upper() not in result
        result[name.upper()] = value
    for group, values in s['enums'].items():
        for name, value in values.items():
            key = f'{group}_{name}'.upper()
            assert key not in result
            result[key] = value
    return result


def outputs(s):
    stem = f"{s['name']}_v{s['version']}"
    prefix = 'MNM_' + stem.upper()
    values = constants(s)
    c = ['/* Generated by protocols/generate.py. Edit the schema instead. */',
         f'#ifndef {prefix}_H', f'#define {prefix}_H',
         f'#define {prefix}_MAGIC "{s["magic"]}"']
    c += [f'#define {prefix}_{key} {value}u' for key, value in values.items()]
    c += ['#endif', '']
    py = ['# Generated by protocols/generate.py. Edit the schema instead.',
          f'MAGIC = {s["magic"].encode("ascii")!r}']
    py += [f'{key} = {value}' for key, value in values.items()]
    # These helpers operate on private bytes, never on an active shared mapping.
    py += ['', 'def initial_header():',
           '    """Return zeroed header bytes for an exclusively owned new file."""',
           '    import struct', '    data = bytearray(HEADER_SIZE)',
           '    data[:8] = MAGIC',
           "    struct.pack_into('<II', data, 8, VERSION, DECLARED_SIZE)",
           '    return bytes(data)', '',
           'def valid_header(data, file_size):',
           '    """Validate identity and file length in a private header snapshot."""',
           '    import struct',
           '    return (file_size == SIZE and len(data) >= HEADER_SIZE',
           '            and data[:8] == MAGIC',
           "            and struct.unpack_from('<II', data, 8) == (VERSION, DECLARED_SIZE))", '']
    return {ROOT/'include'/'mnm'/f'{stem}.h': '\n'.join(c),
            ROOT/'python'/'mnm_protocols'/f'{stem}.py': '\n'.join(py)}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Check bindings without writing')
    args = parser.parse_args()
    failed = []
    for path in sorted((ROOT/'schemas').glob('*.json')):
        s = json.loads(path.read_text())
        validate(s)
        for target, content in outputs(s).items():
            if args.check:
                if not target.exists() or target.read_text() != content:
                    failed.append(str(target.relative_to(ROOT)))
            else:
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(content)
    if failed:
        parser.exit(1, 'Bindings need regeneration: ' + ', '.join(failed) + '\n')
    print('Protocol bindings are current.' if args.check else 'Protocol bindings generated.')


if __name__ == '__main__':
    main()
