cmake_minimum_required(VERSION 3.16)
project(mnm_effect_animation_catalog LANGUAGES CXX)
add_subdirectory(../../../assets assets)
add_subdirectory(../effect-animation-binding binding)
add_library(mnm-effect-animation-catalog-binding STATIC ../effect_animation_catalog_binding.cpp)
target_link_libraries(mnm-effect-animation-catalog-binding PUBLIC mnm-effect-animation-catalog mnm-effect-animation-binding)
target_compile_options(mnm-effect-animation-catalog-binding PRIVATE -Wall -Wextra -Werror -pedantic)
add_executable(effect-animation-catalog-test ../../../tests/effect-animation-catalog-test.cpp)
target_link_libraries(effect-animation-catalog-test PRIVATE mnm-effect-animation-catalog-binding mnm-sprite-loader)
target_compile_options(effect-animation-catalog-test PRIVATE -Wall -Wextra -Werror -pedantic)
include(CTest)
add_test(NAME effect-animation-catalog COMMAND effect-animation-catalog-test)
