# Generated by protocols/generate.py. Edit the schema instead.
MAGIC = b'MNMINK01'
VERSION = 1
SIZE = 1088
HEADER_SIZE = 64
DECLARED_SIZE = 1088
MAGIC_OFFSET = 0
MAGIC_SIZE = 8
VERSION_OFFSET = 8
VERSION_SIZE = 4
DECLARED_SIZE_OFFSET = 12
DECLARED_SIZE_SIZE = 4
SEQUENCE_OFFSET = 16
SEQUENCE_SIZE = 4
ACTIVE_OFFSET = 20
ACTIVE_SIZE = 4
CURSOR_X_OFFSET = 24
CURSOR_X_SIZE = 4
CURSOR_Y_OFFSET = 28
CURSOR_Y_SIZE = 4
WIDTH_OFFSET = 32
WIDTH_SIZE = 4
HEIGHT_OFFSET = 36
HEIGHT_SIZE = 4
RESERVED_OFFSET = 40
RESERVED_SIZE = 24
KEYS_OFFSET = 64
KEYS_SIZE = 1024
KEY_COUNT = 256
KEY_DOWN_MASK = 2147483648
KEY_GENERATION_MASK = 2147483647
MAX_WIDTH = 2048
MAX_HEIGHT = 2048
HEARTBEAT_MS = 50
LEASE_MS = 500

def initial_header():
    """Return zeroed header bytes for an exclusively owned new file."""
    import struct
    data = bytearray(HEADER_SIZE)
    data[:8] = MAGIC
    struct.pack_into('<II', data, 8, VERSION, DECLARED_SIZE)
    return bytes(data)

def valid_header(data, file_size):
    """Validate identity and file length in a private header snapshot."""
    import struct
    return (file_size == SIZE and len(data) >= HEADER_SIZE
            and data[:8] == MAGIC
            and struct.unpack_from('<II', data, 8) == (VERSION, DECLARED_SIZE))
