# Generated by protocols/generate.py. Edit the schema instead.
MAGIC = b'MNMRDC02'
VERSION = 2
SIZE = 1048640
HEADER_SIZE = 64
DECLARED_SIZE = 1048640
MAGIC_OFFSET = 0
MAGIC_SIZE = 8
VERSION_OFFSET = 8
VERSION_SIZE = 4
DECLARED_SIZE_OFFSET = 12
DECLARED_SIZE_SIZE = 4
SESSION_OFFSET = 16
SESSION_SIZE = 4
PUBLISHED_OFFSET = 20
PUBLISHED_SIZE = 4
STATE_OFFSET = 24
STATE_SIZE = 4
REASON_OFFSET = 28
REASON_SIZE = 4
CANCEL_OFFSET = 32
CANCEL_SIZE = 4
ACKNOWLEDGED_OFFSET = 36
ACKNOWLEDGED_SIZE = 4
RESERVED_OFFSET = 40
RESERVED_SIZE = 24
COMMANDS_OFFSET = 64
COMMANDS_SIZE = 1048576
CAPACITY = 1048576
POLL_BYTES = 65536
STATE_READY = 0
STATE_WRITING = 1
STATE_ENDED = 2
STATE_FAILED = 3
REASON_NONE = 0
REASON_OVERFLOW = 1
REASON_GAP = 2
REASON_CANCELLED = 3
REASON_INTERRUPTED = 4
REASON_INVALID = 5

def initial_header():
    """Return zeroed header bytes for an exclusively owned new file."""
    import struct
    data = bytearray(HEADER_SIZE)
    data[:8] = MAGIC
    struct.pack_into('<II', data, 8, VERSION, DECLARED_SIZE)
    return bytes(data)

def valid_header(data, file_size):
    """Validate identity and file length in a private header snapshot."""
    import struct
    return (file_size == SIZE and len(data) >= HEADER_SIZE
            and data[:8] == MAGIC
            and struct.unpack_from('<II', data, 8) == (VERSION, DECLARED_SIZE))
