# Generated by protocols/generate.py. Edit the schema instead.
MAGIC = b'MNMCMD03'
VERSION = 3
SIZE = 16
HEADER_SIZE = 16
DECLARED_SIZE = 16
MAGIC_OFFSET = 0
MAGIC_SIZE = 8
VERSION_OFFSET = 8
VERSION_SIZE = 4
DECLARED_SIZE_OFFSET = 12
DECLARED_SIZE_SIZE = 4
PALETTE_CAPACITY = 32
PALETTE_ENTRIES = 256
CLIP_REGION_CAPACITY = 32
SURFACE_COPY_WORDS = 13
CLIPPER_FIXED_BYTES = 12
CLIP_RECT_BYTES = 16
OPERATION_PALETTE_CREATE = 12
OPERATION_PALETTE_UPDATE = 13
OPERATION_PALETTE_BIND = 14
OPERATION_PALETTE_DELETE = 15
OPERATION_CLIPPER_SET = 16
OPERATION_SURFACE_COPY = 17
OPERATION_SURFACE_RESULT_CHECK = 18
CLIP_MODE_DETACHED = 0
CLIP_MODE_REGIONS = 1
CLIP_MODE_MISSING_LIST = 2
COPY_API_BLT = 0
COPY_API_BLTFAST = 1

def initial_header():
    """Return zeroed header bytes for an exclusively owned new file."""
    import struct
    data = bytearray(HEADER_SIZE)
    data[:8] = MAGIC
    struct.pack_into('<II', data, 8, VERSION, DECLARED_SIZE)
    return bytes(data)

def valid_header(data, file_size):
    """Validate identity and file length in a private header snapshot."""
    import struct
    return (file_size == SIZE and len(data) >= HEADER_SIZE
            and data[:8] == MAGIC
            and struct.unpack_from('<II', data, 8) == (VERSION, DECLARED_SIZE))
