cmake_minimum_required(VERSION 3.16)
project(mnm_effect_motion_initializer LANGUAGES CXX)
add_library(mnm-effect-motion-initializer STATIC ../effect_motion_initializer.cpp ../effect_trajectory_initializer.cpp ../effect_trajectory.cpp)
target_compile_features(mnm-effect-motion-initializer PUBLIC cxx_std_17)
target_include_directories(mnm-effect-motion-initializer PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/..")
target_compile_options(mnm-effect-motion-initializer PRIVATE -Wall -Wextra -Werror -pedantic)
include(CTest)
if(BUILD_TESTING)
    add_executable(effect-motion-initializer-test ../../../tests/effect-motion-initializer-test.cpp)
    target_link_libraries(effect-motion-initializer-test PRIVATE mnm-effect-motion-initializer)
    target_compile_options(effect-motion-initializer-test PRIVATE -Wall -Wextra -Werror -pedantic)
    add_test(NAME effect-motion-initializer COMMAND effect-motion-initializer-test)
endif()
