cmake_minimum_required(VERSION 3.16)
project(mnm_effect_animation_binding LANGUAGES CXX)
add_library(mnm-effect-animation-binding STATIC ../effect_animation_binding.cpp ../effect_animation_selection.cpp ../../animation/no_cd.cpp)
target_compile_features(mnm-effect-animation-binding PUBLIC cxx_std_17)
target_include_directories(mnm-effect-animation-binding PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/.." "${CMAKE_CURRENT_SOURCE_DIR}/../../animation" "${CMAKE_CURRENT_SOURCE_DIR}/../../../assets")
target_compile_options(mnm-effect-animation-binding PRIVATE -Wall -Wextra -Werror -pedantic)
include(CTest)
if(BUILD_TESTING)
    add_executable(effect-animation-binding-test ../../../tests/effect-animation-binding-test.cpp)
    target_link_libraries(effect-animation-binding-test PRIVATE mnm-effect-animation-binding)
    target_compile_options(effect-animation-binding-test PRIVATE -Wall -Wextra -Werror -pedantic)
    add_test(NAME effect-animation-binding COMMAND effect-animation-binding-test)
endif()
