cmake_minimum_required(VERSION 3.16)
project(mnm_effect_animation_metadata LANGUAGES CXX)
add_subdirectory(../../../assets assets)
add_library(mnm-effect-animation-metadata STATIC ../effect_animation_metadata.cpp)
target_include_directories(mnm-effect-animation-metadata PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/..")
target_compile_features(mnm-effect-animation-metadata PUBLIC cxx_std_17)
target_compile_options(mnm-effect-animation-metadata PRIVATE -Wall -Wextra -Werror -pedantic)
add_executable(effect-animation-metadata-reference ../../../tests/effect-animation-metadata-reference.cpp)
target_link_libraries(effect-animation-metadata-reference PRIVATE mnm-effect-animation-metadata mnm-effect-animation-catalog)
target_compile_options(effect-animation-metadata-reference PRIVATE -Wall -Wextra -Werror -pedantic)
add_executable(effect-animation-metadata-test ../../../tests/effect-animation-metadata-test.cpp)
target_link_libraries(effect-animation-metadata-test PRIVATE mnm-effect-animation-metadata)
target_compile_options(effect-animation-metadata-test PRIVATE -Wall -Wextra -Werror -pedantic)
include(CTest)
add_test(NAME effect-animation-metadata COMMAND effect-animation-metadata-test)
