#!/usr/bin/env python3
"""Generate a reviewed, build-pinned World raster caller whitelist from observed sources."""
import argparse,hashlib,importlib.util,json,struct,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
HASH='40209ca76705b5db04ea1974543bdec1739c68acdebdbefe2537ed025b8b7168'
def main():
 p=argparse.ArgumentParser();p.add_argument('--stream',type=Path,required=True);p.add_argument('--header',type=Path,required=True);p.add_argument('--report',type=Path,required=True);a=p.parse_args()
 subprocess.run([ROOT/'tools/original-manifest.sh','verify'],check=True)
 try:
  exe=ROOT/'original/Arcane_Nocd/Chaos.exe';raw=exe.read_bytes();assert hashlib.sha256(raw).hexdigest()==HASH
  pe=struct.unpack_from('<I',raw,60)[0];ns,opt=struct.unpack_from('<H',raw,pe+6)[0],struct.unpack_from('<H',raw,pe+20)[0]
  def at(va,n):
   for i in range(ns):
    row=pe+24+opt+i*40;size,rva,rs,off=struct.unpack_from('<4I',raw,row+8);d=va-0x400000-rva
    if 0<=d and d+n<=rs:return raw[off+d:off+d+n]
   raise ValueError('Unbacked caller')
  s=importlib.util.spec_from_file_location('inspector',ROOT/'tools/inspect-canvas-producers.py');m=importlib.util.module_from_spec(s);s.loader.exec_module(m);_,ops=m.decode(a.stream.read_bytes())
  callers={};active=False;tags={0:[12],1:[13,14],2:[15,16],3:[17],4:[18],5:[19],6:[20],7:[21],9:[23,24],10:[25]}
  for r,_ in ops:
   if r[2]==11:active=True
   elif r[2]==12:active=False
   elif active and r[2]==9:
    if r[15] not in tags:raise ValueError('Unreviewed raster backend')
    callers.setdefault(r[22],set()).update(tags[r[15]])
  rows=[];header=['/* Generated by inspect-world-raster-callers.py from pinned observed caller sources. */','static const struct RasterCaller {u32 address,tags;u8 bytes[10];} raster_callers[]={']
  for va,ts in sorted(callers.items()):
   # These ranges were reviewed through the AX stores/masks and queue loop.
   if not (0x5002a0<=va<0x501150 or 0x57e8e0<=va<0x57eb00):raise ValueError('Caller outside reviewed World/wrapper range')
   sig=at(va,10);mask=sum(1<<t for t in ts);header.append(' {0x%x,0x%x,{%s}},'%(va,mask,','.join(hex(x) for x in sig)))
   asm=subprocess.check_output(['objdump','-d','-Mintel','--start-address='+hex(va),'--stop-address='+hex(min(va+80,0x501150 if va<0x501150 else 0x57eb00)),str(exe)],text=True)
   rows.append({'address':hex(va),'tags':sorted(ts),'return_signature':sig.hex(),'disassembly':asm,'scope':'Observed return path consumes low16 AX only; callee-saved registers preserved, volatile registers/flags overwritten before subsequent use on reviewed path.'})
  header+=['};'];a.header.open('x').write('\n'.join(header)+'\n')
  report={'success':True,'source_executable_sha256':HASH,'caller_count':len(rows),'callers':rows,'sources':{str(Path(__file__).relative_to(ROOT)):hashlib.sha256(Path(__file__).read_bytes()).hexdigest()},'input_stream':{'path':str(a.stream),'sha256':hashlib.sha256(a.stream.read_bytes()).hexdigest()},'generated_header_sha256':hashlib.sha256(a.header.read_bytes()).hexdigest(),'scope':'Static observed-caller whitelist and bytes; not pixel equivalence or whole-function recovery.'};a.report.open('x').write(json.dumps(report,indent=2)+'\n')
 finally:subprocess.run([ROOT/'tools/original-manifest.sh','verify'],check=True)
if __name__=='__main__':main()
