cmake_minimum_required(VERSION 3.16)
project(mnm_word_raster LANGUAGES C)
set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_C_EXTENSIONS OFF)
add_library(mnm-word-raster STATIC ../word_raster.c)
target_include_directories(mnm-word-raster PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/..")
target_compile_options(mnm-word-raster PRIVATE -Wall -Wextra -Werror -pedantic)
include(CTest)
if(BUILD_TESTING)
    add_executable(word-raster-test ../../../tests/word-raster-test.c)
    target_link_libraries(word-raster-test PRIVATE mnm-word-raster)
    target_compile_options(word-raster-test PRIVATE -Wall -Wextra -Werror -pedantic)
    add_test(NAME native-word-raster COMMAND word-raster-test)
endif()
